import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core'
import { sql } from 'drizzle-orm'

export const universe = sqliteTable('universe', {
  id:         integer('id').primaryKey({ autoIncrement: true }),
  ticker:     text('ticker').notNull().unique(),
  name:       text('name'),
  exchange:   text('exchange'),
  country:    text('country'),
  region:     text('region'),
  currency:   text('currency'),
  sector:     text('sector'),
  industry:   text('industry'),
  market_cap: real('market_cap'),
  asset_type: text('asset_type'),
  is_active:  integer('is_active').default(1),
  added_at:   text('added_at').default(sql`(datetime('now'))`),
})

export const priceSnapshots = sqliteTable('price_snapshots', {
  id:                     integer('id').primaryKey({ autoIncrement: true }),
  ticker:                 text('ticker').notNull(),
  fetched_at:             text('fetched_at').notNull(),
  price:                  real('price'),
  pe:                     real('pe'),
  pb:                     real('pb'),
  ps:                     real('ps'),
  ev_ebitda:              real('ev_ebitda'),
  eps:                    real('eps'),
  eps_growth_yoy:         real('eps_growth_yoy'),
  revenue_growth_yoy:     real('revenue_growth_yoy'),
  gross_margin:           real('gross_margin'),
  operating_margin:       real('operating_margin'),
  roe:                    real('roe'),
  debt_equity:            real('debt_equity'),
  free_cash_flow:         real('free_cash_flow'),
  dividend_yield:         real('dividend_yield'),
  short_percent_of_float: real('short_percent_of_float'),
  analyst_buy:            integer('analyst_buy'),
  analyst_hold:           integer('analyst_hold'),
  analyst_sell:           integer('analyst_sell'),
  price_target:           real('price_target'),
  earnings_date:          text('earnings_date'),
  high_52w:               real('high_52w'),
  low_52w:                real('low_52w'),
  beta:                   real('beta'),
  sma_20:                 real('sma_20'),
  sma_50:                 real('sma_50'),
  sma_200:                real('sma_200'),
  rsi_14:                 real('rsi_14'),
  macd:                   real('macd'),
  macd_signal:            real('macd_signal'),
  volume:                 real('volume'),
  avg_volume:             real('avg_volume'),
})

export const insiderTransactions = sqliteTable('insider_transactions', {
  id:                 integer('id').primaryKey({ autoIncrement: true }),
  ticker:             text('ticker').notNull(),
  filed_at:           text('filed_at'),
  transaction_date:   text('transaction_date'),
  insider_name:       text('insider_name'),
  relation:           text('relation'),
  transaction_type:   text('transaction_type'),
  shares:             real('shares'),
  value:              real('value'),
  fetched_at:         text('fetched_at'),
  is_open_market_buy: integer('is_open_market_buy').default(0),
})
