/**
 * Batch sector + name lookup for all tickers currently stored as "Other"
 * Sources: authoritative hardcoded maps based on known listed companies
 * Run with: npx tsx scripts/batchSectorLookup.ts
 */

import Database from "better-sqlite3";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DB_PATH = process.env.DB_PATH || path.join(__dirname, "../stock-recommender.db");
const db = new Database(DB_PATH);

// ─── Master lookup map: ticker → { name, sector } ────────────────────────────
// Covers all major Asian, European and residual US tickers found in Other.

type Entry = { name: string; sector: string };
const LOOKUP: Record<string, Entry> = {

  // ══════════════════════════════════════════════════════════════════════════
  // JAPAN (.T) — TSE listed companies
  // ══════════════════════════════════════════════════════════════════════════
  "2002.T":  { name: "Nisshin Seifun Group", sector: "Consumer Staples" },
  "2413.T":  { name: "M3 Inc.", sector: "Healthcare" },
  "2501.T":  { name: "Sapporo Holdings", sector: "Consumer Staples" },
  "2502.T":  { name: "Asahi Group Holdings", sector: "Consumer Staples" },
  "2503.T":  { name: "Kirin Holdings", sector: "Consumer Staples" },
  "2531.T":  { name: "Takara Holdings", sector: "Consumer Staples" },
  "2914.T":  { name: "Japan Tobacco International", sector: "Consumer Staples" },
  "3086.T":  { name: "J.Front Retailing", sector: "Retail & Leisure" },
  "3101.T":  { name: "Toyobo Co.", sector: "Materials" },
  "3105.T":  { name: "Nisshinbo Holdings", sector: "Industrials" },
  "3289.T":  { name: "Tokyu Fudosan Holdings", sector: "Real Estate" },
  "3333.T":  { name: "Aeon Mall Co.", sector: "Real Estate" },
  "3382.T":  { name: "Seven & i Holdings", sector: "Retail & Leisure" },
  "3402.T":  { name: "Toray Industries", sector: "Materials" },
  "3407.T":  { name: "Asahi Kasei Corp.", sector: "Materials" },
  "3591.T":  { name: "Wacoal Holdings", sector: "Retail & Leisure" },
  "4042.T":  { name: "Tosoh Corp.", sector: "Materials" },
  "4063.T":  { name: "Shin-Etsu Chemical", sector: "Materials" },
  "4151.T":  { name: "Kyowa Kirin Co.", sector: "Healthcare" },
  "4188.T":  { name: "Mitsubishi Chemical Group", sector: "Materials" },
  "4452.T":  { name: "Kao Corp.", sector: "Consumer Staples" },
  "4502.T":  { name: "Takeda Pharmaceutical", sector: "Healthcare" },
  "4503.T":  { name: "Astellas Pharma", sector: "Healthcare" },
  "4507.T":  { name: "Shionogi & Co.", sector: "Healthcare" },
  "4516.T":  { name: "Nippon Shinyaku Co.", sector: "Healthcare" },
  "4519.T":  { name: "Chugai Pharmaceutical", sector: "Healthcare" },
  "4523.T":  { name: "Eisai Co.", sector: "Healthcare" },
  "4528.T":  { name: "Ono Pharmaceutical", sector: "Healthcare" },
  "4543.T":  { name: "Terumo Corp.", sector: "Healthcare" },
  "4568.T":  { name: "Daiichi Sankyo", sector: "Healthcare" },
  "4581.T":  { name: "Taisho Pharmaceutical", sector: "Healthcare" },
  "4661.T":  { name: "Oriental Land Co.", sector: "Retail & Leisure" },
  "4704.T":  { name: "Trend Micro Inc.", sector: "Technology" },
  "4901.T":  { name: "Fujifilm Holdings", sector: "Technology" },
  "4911.T":  { name: "Shiseido Co.", sector: "Consumer Staples" },
  "5108.T":  { name: "Bridgestone Corp.", sector: "Automotive" },
  "5202.T":  { name: "Nippon Sheet Glass", sector: "Materials" },
  "5401.T":  { name: "Nippon Steel Corp.", sector: "Materials" },
  "5713.T":  { name: "Sumitomo Metal Mining", sector: "Materials" },
  "5714.T":  { name: "DOWA Holdings", sector: "Materials" },
  "6103.T":  { name: "Okuma Corp.", sector: "Industrials" },
  "6301.T":  { name: "Komatsu Ltd.", sector: "Industrials" },
  "6326.T":  { name: "Kubota Corp.", sector: "Industrials" },
  "6366.T":  { name: "Chiyoda Corp.", sector: "Industrials" },
  "6367.T":  { name: "Daikin Industries", sector: "Industrials" },
  "6471.T":  { name: "NSK Ltd.", sector: "Industrials" },
  "6479.T":  { name: "Minebea Mitsumi", sector: "Industrials" },
  "6501.T":  { name: "Hitachi Ltd.", sector: "Technology" },
  "6503.T":  { name: "Mitsubishi Electric", sector: "Technology" },
  "6506.T":  { name: "Yaskawa Electric", sector: "Industrials" },
  "6594.T":  { name: "Nidec Corp.", sector: "Industrials" },
  "6645.T":  { name: "Omron Corp.", sector: "Industrials" },
  "6702.T":  { name: "Fujitsu Ltd.", sector: "Technology" },
  "6723.T":  { name: "Renesas Electronics", sector: "Technology" },
  "6752.T":  { name: "Panasonic Holdings", sector: "Technology" },
  "6758.T":  { name: "Sony Group Corp.", sector: "Technology" },
  "6841.T":  { name: "Yokogawa Electric", sector: "Technology" },
  "6857.T":  { name: "Advantest Corp.", sector: "Technology" },
  "6861.T":  { name: "Keyence Corp.", sector: "Technology" },
  "6902.T":  { name: "DENSO Corp.", sector: "Automotive" },
  "6920.T":  { name: "Lasertec Corp.", sector: "Technology" },
  "6954.T":  { name: "Fanuc Corp.", sector: "Industrials" },
  "6963.T":  { name: "Rohm Co.", sector: "Technology" },
  "6971.T":  { name: "Kyocera Corp.", sector: "Technology" },
  "6988.T":  { name: "Nitto Denko Corp.", sector: "Materials" },
  "7004.T":  { name: "Hitachi Zosen Corp.", sector: "Industrials" },
  "7011.T":  { name: "Mitsubishi Heavy Industries", sector: "Defense & Aerospace" },
  "7012.T":  { name: "Kawasaki Heavy Industries", sector: "Industrials" },
  "7013.T":  { name: "IHI Corp.", sector: "Industrials" },
  "7201.T":  { name: "Nissan Motor Co.", sector: "Automotive" },
  "7203.T":  { name: "Toyota Motor Corp.", sector: "Automotive" },
  "7241.T":  { name: "Futaba Corp.", sector: "Automotive" },
  "7259.T":  { name: "Aisin Corp.", sector: "Automotive" },
  "7261.T":  { name: "Mazda Motor Corp.", sector: "Automotive" },
  "7267.T":  { name: "Honda Motor Co.", sector: "Automotive" },
  "7269.T":  { name: "Suzuki Motor Corp.", sector: "Automotive" },
  "7272.T":  { name: "Yamaha Motor Co.", sector: "Automotive" },
  "7296.T":  { name: "F.C.C. Co.", sector: "Automotive" },
  "7309.T":  { name: "Shimano Inc.", sector: "Industrials" },
  "7731.T":  { name: "Nikon Corp.", sector: "Technology" },
  "7733.T":  { name: "Olympus Corp.", sector: "Healthcare" },
  "7735.T":  { name: "Screen Holdings", sector: "Technology" },
  "7741.T":  { name: "Hoya Corp.", sector: "Healthcare" },
  "7751.T":  { name: "Canon Inc.", sector: "Technology" },
  "7762.T":  { name: "Citizen Watch Co.", sector: "Industrials" },
  "7832.T":  { name: "Bandai Namco Holdings", sector: "Retail & Leisure" },
  "7974.T":  { name: "Nintendo Co.", sector: "Retail & Leisure" },
  "8001.T":  { name: "Itochu Corp.", sector: "Industrials" },
  "8002.T":  { name: "Marubeni Corp.", sector: "Industrials" },
  "8003.T":  { name: "Toyo Suisan Kaisha", sector: "Consumer Staples" },
  "8015.T":  { name: "Toyota Tsusho Corp.", sector: "Industrials" },
  "8031.T":  { name: "Mitsui & Co.", sector: "Industrials" },
  "8053.T":  { name: "Sumitomo Corp.", sector: "Industrials" },
  "8058.T":  { name: "Mitsubishi Corp.", sector: "Industrials" },
  "8306.T":  { name: "Mitsubishi UFJ Financial Group", sector: "Financials" },
  "8309.T":  { name: "Sumitomo Mitsui Trust Holdings", sector: "Financials" },
  "8316.T":  { name: "Sumitomo Mitsui Financial Group", sector: "Financials" },
  "8332.T":  { name: "Bank of Yokohama", sector: "Financials" },
  "8354.T":  { name: "Fukuoka Financial Group", sector: "Financials" },
  "8411.T":  { name: "Mizuho Financial Group", sector: "Financials" },
  "8725.T":  { name: "MS&AD Insurance Group", sector: "Financials" },
  "8801.T":  { name: "Mitsui Fudosan Co.", sector: "Real Estate" },
  "8802.T":  { name: "Mitsubishi Estate Co.", sector: "Real Estate" },
  "9001.T":  { name: "Tobu Railway Co.", sector: "Industrials" },
  "9005.T":  { name: "Tokyu Corp.", sector: "Industrials" },
  "9009.T":  { name: "Keisei Electric Railway", sector: "Industrials" },
  "9020.T":  { name: "East Japan Railway Co.", sector: "Industrials" },
  "9021.T":  { name: "West Japan Railway Co.", sector: "Industrials" },
  "9022.T":  { name: "Central Japan Railway Co.", sector: "Industrials" },
  "9064.T":  { name: "Yamato Holdings", sector: "Industrials" },
  "9101.T":  { name: "Nippon Yusen K.K.", sector: "Industrials" },
  "9432.T":  { name: "Nippon Telegraph and Telephone", sector: "Communication Services" },
  "9433.T":  { name: "KDDI Corp.", sector: "Communication Services" },
  "9613.T":  { name: "NTT Data Group Corp.", sector: "Technology" },
  "9766.T":  { name: "Konami Group Corp.", sector: "Retail & Leisure" },
  "9974.T":  { name: "Belc Co.", sector: "Retail & Leisure" },
  "9983.T":  { name: "Fast Retailing Co.", sector: "Retail & Leisure" },
  "9984.T":  { name: "SoftBank Group Corp.", sector: "Technology" },

  // ══════════════════════════════════════════════════════════════════════════
  // HONG KONG (.HK)
  // ══════════════════════════════════════════════════════════════════════════
  "0001.HK": { name: "CK Hutchison Holdings", sector: "Industrials" },
  "0002.HK": { name: "CLP Holdings", sector: "Utilities" },
  "0003.HK": { name: "Hong Kong & China Gas", sector: "Utilities" },
  "0005.HK": { name: "HSBC Holdings (HK)", sector: "Financials" },
  "0006.HK": { name: "Power Assets Holdings", sector: "Utilities" },
  "0011.HK": { name: "Hang Seng Bank", sector: "Financials" },
  "0012.HK": { name: "Henderson Land Development", sector: "Real Estate" },
  "0016.HK": { name: "Sun Hung Kai Properties", sector: "Real Estate" },
  "0017.HK": { name: "New World Development", sector: "Real Estate" },
  "0019.HK": { name: "Swire Pacific", sector: "Industrials" },
  "0066.HK": { name: "MTR Corp.", sector: "Industrials" },
  "0101.HK": { name: "Hang Lung Properties", sector: "Real Estate" },
  "0135.HK": { name: "Kun Lung Const.", sector: "Real Estate" },
  "0175.HK": { name: "Geely Automobile Holdings", sector: "Automotive" },
  "0267.HK": { name: "CITIC Ltd.", sector: "Industrials" },
  "0291.HK": { name: "China Resources Beer", sector: "Consumer Staples" },
  "0316.HK": { name: "Orient Overseas International", sector: "Industrials" },
  "0386.HK": { name: "China Petroleum & Chemical (Sinopec)", sector: "Energy – Oil & Gas" },
  "0388.HK": { name: "Hong Kong Exchanges and Clearing", sector: "Financials" },
  "0669.HK": { name: "Techtronic Industries", sector: "Industrials" },
  "0688.HK": { name: "China Overseas Land & Investment", sector: "Real Estate" },
  "0700.HK": { name: "Tencent Holdings", sector: "Technology" },
  "0762.HK": { name: "China Unicom (HK)", sector: "Communication Services" },
  "0823.HK": { name: "Link REIT", sector: "Real Estate" },
  "0836.HK": { name: "China Resources Power Holdings", sector: "Utilities" },
  "0857.HK": { name: "PetroChina Co.", sector: "Energy – Oil & Gas" },
  "0868.HK": { name: "Xinyi Glass Holdings", sector: "Materials" },
  "0883.HK": { name: "CNOOC Ltd.", sector: "Energy – Oil & Gas" },
  "0939.HK": { name: "China Construction Bank", sector: "Financials" },
  "0941.HK": { name: "China Mobile Ltd.", sector: "Communication Services" },
  "0960.HK": { name: "Longfor Group Holdings", sector: "Real Estate" },
  "0992.HK": { name: "Lenovo Group", sector: "Technology" },
  "1024.HK": { name: "Kuaishou Technology", sector: "Technology" },
  "1038.HK": { name: "CK Infrastructure Holdings", sector: "Utilities" },
  "1044.HK": { name: "Hengan International Group", sector: "Consumer Staples" },
  "1093.HK": { name: "CSPC Pharmaceutical Group", sector: "Healthcare" },
  "1109.HK": { name: "China Resources Land", sector: "Real Estate" },
  "1113.HK": { name: "CK Asset Holdings", sector: "Real Estate" },
  "1177.HK": { name: "Sino Biopharmaceutical", sector: "Healthcare" },
  "1211.HK": { name: "BYD Co.", sector: "Automotive" },
  "1288.HK": { name: "Agricultural Bank of China", sector: "Financials" },
  "1299.HK": { name: "AIA Group", sector: "Financials" },
  "1336.HK": { name: "New China Life Insurance", sector: "Financials" },
  "1378.HK": { name: "China Hongqiao Group", sector: "Materials" },
  "1398.HK": { name: "Industrial and Commercial Bank of China", sector: "Financials" },
  "1810.HK": { name: "Xiaomi Corp.", sector: "Technology" },
  "1876.HK": { name: "Budweiser Brewing Company APAC", sector: "Consumer Staples" },
  "1929.HK": { name: "Chow Tai Fook Jewellery", sector: "Retail & Leisure" },
  "2007.HK": { name: "Country Garden Holdings", sector: "Real Estate" },
  "2015.HK": { name: "Li Auto Inc.", sector: "Automotive" },
  "2020.HK": { name: "ANTA Sports Products", sector: "Retail & Leisure" },
  "2269.HK": { name: "WuXi Biologics", sector: "Healthcare" },
  "2313.HK": { name: "Shenzhou International Group", sector: "Retail & Leisure" },
  "2318.HK": { name: "Ping An Insurance", sector: "Financials" },
  "2382.HK": { name: "Sunny Optical Technology", sector: "Technology" },
  "2388.HK": { name: "BOC Hong Kong Holdings", sector: "Financials" },
  "2628.HK": { name: "China Life Insurance", sector: "Financials" },
  "2688.HK": { name: "ENN Energy Holdings", sector: "Utilities" },
  "3690.HK": { name: "Meituan", sector: "Technology" },
  "3988.HK": { name: "Bank of China", sector: "Financials" },
  "6098.HK": { name: "Country Garden Services Holdings", sector: "Real Estate" },
  "6862.HK": { name: "Haidilao International Holding", sector: "Retail & Leisure" },
  "9618.HK": { name: "JD.com (HK)", sector: "Retail & Leisure" },
  "9888.HK": { name: "Baidu Inc. (HK)", sector: "Technology" },
  "9988.HK": { name: "Alibaba Group (HK)", sector: "Technology" },
  "9999.HK": { name: "NetEase (HK)", sector: "Technology" },

  // ══════════════════════════════════════════════════════════════════════════
  // SOUTH KOREA (.KS)
  // ══════════════════════════════════════════════════════════════════════════
  "000080.KS": { name: "Hite Jinro Co.", sector: "Consumer Staples" },
  "000270.KS": { name: "Kia Corp.", sector: "Automotive" },
  "000660.KS": { name: "SK Hynix Inc.", sector: "Technology" },
  "000810.KS": { name: "Samsung Fire & Marine Insurance", sector: "Financials" },
  "000990.KS": { name: "DB HiTek Co.", sector: "Technology" },
  "001450.KS": { name: "Hyundai Marine & Fire Insurance", sector: "Financials" },
  "003490.KS": { name: "Korean Air Lines Co.", sector: "Industrials" },
  "003550.KS": { name: "LG Corp.", sector: "Industrials" },
  "003670.KS": { name: "POSCO Future M Co.", sector: "Materials" },
  "004020.KS": { name: "Hyundai Steel Co.", sector: "Materials" },
  "004170.KS": { name: "Shinsegae Co.", sector: "Retail & Leisure" },
  "005380.KS": { name: "Hyundai Motor Co.", sector: "Automotive" },
  "005490.KS": { name: "POSCO Holdings", sector: "Materials" },
  "005930.KS": { name: "Samsung Electronics", sector: "Technology" },
  "006400.KS": { name: "Samsung SDI Co.", sector: "Technology" },
  "006800.KS": { name: "Mirae Asset Securities", sector: "Financials" },
  "009150.KS": { name: "Samsung Electro-Mechanics", sector: "Technology" },
  "010130.KS": { name: "Korea Zinc Co.", sector: "Materials" },
  "010140.KS": { name: "Samsung Heavy Industries", sector: "Industrials" },
  "010950.KS": { name: "S-Oil Corp.", sector: "Energy – Oil & Gas" },
  "011200.KS": { name: "HMM Co.", sector: "Industrials" },
  "011780.KS": { name: "Kumho Petrochemical Co.", sector: "Materials" },
  "012330.KS": { name: "Hyundai Mobis Co.", sector: "Automotive" },
  "012630.KS": { name: "HDC Holdings", sector: "Industrials" },
  "017670.KS": { name: "SK Telecom Co.", sector: "Communication Services" },
  "018260.KS": { name: "Samsung SDS Co.", sector: "Technology" },
  "018880.KS": { name: "Hanon Systems", sector: "Automotive" },
  "021240.KS": { name: "Coway Co.", sector: "Industrials" },
  "028260.KS": { name: "Samsung C&T Corp.", sector: "Industrials" },
  "030200.KS": { name: "KT Corp.", sector: "Communication Services" },
  "032640.KS": { name: "LG Uplus Corp.", sector: "Communication Services" },
  "032830.KS": { name: "Samsung Life Insurance", sector: "Financials" },
  "033780.KS": { name: "KT&G Corp.", sector: "Consumer Staples" },
  "034730.KS": { name: "SK Inc.", sector: "Industrials" },
  "035420.KS": { name: "NAVER Corp.", sector: "Technology" },
  "041510.KS": { name: "SM Entertainment Co.", sector: "Communication Services" },
  "042660.KS": { name: "Daewoo Shipbuilding & Marine Engineering", sector: "Industrials" },
  "047810.KS": { name: "Korea Aerospace Industries", sector: "Defense & Aerospace" },
  "051910.KS": { name: "LG Chem Ltd.", sector: "Materials" },
  "055550.KS": { name: "Shinhan Financial Group", sector: "Financials" },
  "068270.KS": { name: "Celltrion Inc.", sector: "Healthcare" },
  "069960.KS": { name: "Hyundai Department Store", sector: "Retail & Leisure" },
  "078930.KS": { name: "GS Holdings Corp.", sector: "Energy – Oil & Gas" },
  "086280.KS": { name: "Hyundai Glovis Co.", sector: "Industrials" },
  "086790.KS": { name: "Hana Financial Group", sector: "Financials" },
  "090430.KS": { name: "Amorepacific Corp.", sector: "Consumer Staples" },
  "096770.KS": { name: "SK Innovation Co.", sector: "Energy – Oil & Gas" },
  "105560.KS": { name: "KB Financial Group", sector: "Financials" },
  "111770.KS": { name: "Youngone Corp.", sector: "Retail & Leisure" },
  "161390.KS": { name: "Hankook Tire & Technology", sector: "Automotive" },

  // ══════════════════════════════════════════════════════════════════════════
  // TAIWAN (.TW)
  // ══════════════════════════════════════════════════════════════════════════
  "1216.TW": { name: "Uni-President Enterprises", sector: "Consumer Staples" },
  "1301.TW": { name: "Formosa Plastics Corp.", sector: "Materials" },
  "1303.TW": { name: "Nan Ya Plastics Corp.", sector: "Materials" },
  "1605.TW": { name: "Walsin Lihwa Corp.", sector: "Materials" },
  "2002.TW": { name: "China Steel Corp.", sector: "Materials" },
  "2207.TW": { name: "Hotai Motor Co.", sector: "Automotive" },
  "2301.TW": { name: "Lite-On Technology Corp.", sector: "Technology" },
  "2303.TW": { name: "United Microelectronics Corp.", sector: "Technology" },
  "2308.TW": { name: "Delta Electronics Inc.", sector: "Technology" },
  "2317.TW": { name: "Hon Hai Precision (Foxconn)", sector: "Technology" },
  "2325.TW": { name: "Siliconware Precision Industries", sector: "Technology" },
  "2327.TW": { name: "Yageo Corp.", sector: "Technology" },
  "2330.TW": { name: "Taiwan Semiconductor Manufacturing", sector: "Technology" },
  "2337.TW": { name: "Macronix International", sector: "Technology" },
  "2347.TW": { name: "Synnex Technology International", sector: "Technology" },
  "2353.TW": { name: "Acer Inc.", sector: "Technology" },
  "2357.TW": { name: "ASUSTeK Computer Inc.", sector: "Technology" },
  "2379.TW": { name: "Realtek Semiconductor Corp.", sector: "Technology" },
  "2382.TW": { name: "Quanta Computer Inc.", sector: "Technology" },
  "2395.TW": { name: "Advantech Co.", sector: "Technology" },
  "2408.TW": { name: "Nanya Technology Corp.", sector: "Technology" },
  "2412.TW": { name: "Chunghwa Telecom Co.", sector: "Communication Services" },
  "2454.TW": { name: "MediaTek Inc.", sector: "Technology" },
  "2474.TW": { name: "Coretronic Corp.", sector: "Technology" },
  "2609.TW": { name: "Yang Ming Marine Transport Corp.", sector: "Industrials" },
  "2610.TW": { name: "China Airlines Ltd.", sector: "Industrials" },
  "2615.TW": { name: "Wan Hai Lines Ltd.", sector: "Industrials" },
  "2618.TW": { name: "EVA Airways Corp.", sector: "Industrials" },
  "2633.TW": { name: "Taiwan High Speed Rail Corp.", sector: "Industrials" },
  "2880.TW": { name: "Hua Nan Financial Holdings", sector: "Financials" },
  "2881.TW": { name: "Fubon Financial Holding", sector: "Financials" },
  "2882.TW": { name: "Cathay Financial Holding", sector: "Financials" },
  "2884.TW": { name: "E.Sun Financial Holding", sector: "Financials" },
  "2885.TW": { name: "Yuanta Financial Holding", sector: "Financials" },
  "2886.TW": { name: "Mega Financial Holding", sector: "Financials" },
  "2887.TW": { name: "Taishin Financial Holding", sector: "Financials" },
  "2891.TW": { name: "CTBC Financial Holding", sector: "Financials" },
  "2892.TW": { name: "First Financial Holding", sector: "Financials" },
  "3008.TW": { name: "Largan Precision Co.", sector: "Technology" },
  "3034.TW": { name: "Novatek Microelectronics Corp.", sector: "Technology" },
  "3037.TW": { name: "Unimicron Technology Corp.", sector: "Technology" },
  "3045.TW": { name: "Taiwan Mobile Co.", sector: "Communication Services" },
  "3702.TW": { name: "WPG Holdings", sector: "Technology" },
  "3711.TW": { name: "ASE Technology Holding", sector: "Technology" },
  "4904.TW": { name: "Far EasTone Telecommunications", sector: "Communication Services" },
  "5871.TW": { name: "Chailease Holding Co.", sector: "Financials" },
  "5876.TW": { name: "Shanghai Commercial and Savings Bank", sector: "Financials" },
  "6505.TW": { name: "Formosa Petrochemical Corp.", sector: "Energy – Oil & Gas" },
  "9910.TW": { name: "Feng Tay Enterprises Co.", sector: "Retail & Leisure" },

  // ══════════════════════════════════════════════════════════════════════════
  // UK (.L) — London Stock Exchange
  // ══════════════════════════════════════════════════════════════════════════
  "AAF.L":   { name: "Airtel Africa plc", sector: "Communication Services" },
  "AAL.L":   { name: "Anglo American plc", sector: "Materials" },
  "ABF.L":   { name: "Associated British Foods", sector: "Consumer Staples" },
  "ADM.L":   { name: "Admiral Group plc", sector: "Financials" },
  "ALW.L":   { name: "Allow Group plc", sector: "Financials" },
  "ANTO.L":  { name: "Antofagasta plc", sector: "Materials" },
  "AUTO.L":  { name: "Auto Trader Group plc", sector: "Technology" },
  "AV.L":    { name: "Aviva plc", sector: "Financials" },
  "BA.L":    { name: "BAE Systems plc", sector: "Defense & Aerospace" },
  "BAB.L":   { name: "Babcock International Group", sector: "Defense & Aerospace" },
  "BARC.L":  { name: "Barclays plc", sector: "Financials" },
  "BATS.L":  { name: "British American Tobacco plc", sector: "Consumer Staples" },
  "BBOX.L":  { name: "Tritax Big Box REIT", sector: "Real Estate" },
  "BEZ.L":   { name: "Beazley plc", sector: "Financials" },
  "BGEO.L":  { name: "Bank of Georgia Group", sector: "Financials" },
  "BHP.L":   { name: "BHP Group plc (LSE)", sector: "Materials" },
  "BKG.L":   { name: "Berkeley Group Holdings", sector: "Real Estate" },
  "BLND.L":  { name: "British Land Co. plc", sector: "Real Estate" },
  "BNZL.L":  { name: "Bunzl plc", sector: "Industrials" },
  "BRBY.L":  { name: "Burberry Group plc", sector: "Retail & Leisure" },
  "BT.L":    { name: "BT Group plc", sector: "Communication Services" },
  "BTRW.L":  { name: "Barratt Redrow plc", sector: "Real Estate" },
  "CCEP.L":  { name: "Coca-Cola Europacific Partners (LSE)", sector: "Consumer Staples" },
  "CCH.L":   { name: "Coca-Cola HBC AG (LSE)", sector: "Consumer Staples" },
  "CNA.L":   { name: "Centrica plc", sector: "Utilities" },
  "CPG.L":   { name: "Compass Group plc", sector: "Retail & Leisure" },
  "CRDA.L":  { name: "Croda International plc", sector: "Materials" },
  "CTEC.L":  { name: "ConvaTec Group plc", sector: "Healthcare" },
  "DCC.L":   { name: "DCC plc", sector: "Industrials" },
  "DGE.L":   { name: "Diageo plc", sector: "Consumer Staples" },
  "DPLM.L":  { name: "Diploma plc", sector: "Industrials" },
  "EDV.L":   { name: "Endeavour Mining plc", sector: "Materials" },
  "ENT.L":   { name: "Entain plc", sector: "Retail & Leisure" },
  "EXPN.L":  { name: "Experian plc", sector: "Technology" },
  "FCIT.L":  { name: "F&C Investment Trust", sector: "Financials" },
  "FRES.L":  { name: "Fresnillo plc", sector: "Materials" },
  "GAW.L":   { name: "Games Workshop Group plc", sector: "Retail & Leisure" },
  "GBP.L":   { name: "Global Balanced Pref plc", sector: "Financials" },
  "GLEN.L":  { name: "Glencore plc", sector: "Materials" },
  "HLMA.L":  { name: "Halma plc", sector: "Technology" },
  "HLN.L":   { name: "Haleon plc", sector: "Healthcare" },
  "HSBA.L":  { name: "HSBC Holdings plc (LSE)", sector: "Financials" },
  "HSX.L":   { name: "Hiscox Ltd.", sector: "Financials" },
  "HWDN.L":  { name: "Howden Joinery Group plc", sector: "Industrials" },
  "IAG.L":   { name: "International Consolidated Airlines Group", sector: "Industrials" },
  "ICEU.L":  { name: "Intercontinental Exchange (LSE)", sector: "Financials" },
  "ICG.L":   { name: "Intermediate Capital Group", sector: "Financials" },
  "IGG.L":   { name: "IG Group Holdings plc", sector: "Financials" },
  "IHG.L":   { name: "InterContinental Hotels Group", sector: "Retail & Leisure" },
  "III.L":   { name: "3i Group plc", sector: "Financials" },
  "IMB.L":   { name: "Imperial Brands plc", sector: "Consumer Staples" },
  "IMI.L":   { name: "IMI plc", sector: "Industrials" },
  "INF.L":   { name: "Informa plc", sector: "Communication Services" },
  "ITRK.L":  { name: "Intertek Group plc", sector: "Industrials" },
  "ITV.L":   { name: "ITV plc", sector: "Communication Services" },
  "JD.L":    { name: "JD Sports Fashion plc", sector: "Retail & Leisure" },
  "KGF.L":   { name: "Kingfisher plc", sector: "Retail & Leisure" },
  "LAND.L":  { name: "Land Securities Group plc", sector: "Real Estate" },
  "LGEN.L":  { name: "Legal & General Group plc", sector: "Financials" },
  "LLOY.L":  { name: "Lloyds Banking Group plc", sector: "Financials" },
  "LMP.L":   { name: "Londonmetric Property plc", sector: "Real Estate" },
  "LSEG.L":  { name: "London Stock Exchange Group plc", sector: "Financials" },
  "MKS.L":   { name: "Marks and Spencer Group plc", sector: "Retail & Leisure" },
  "MNDI.L":  { name: "Mondi plc", sector: "Materials" },
  "MNG.L":   { name: "M&G plc", sector: "Financials" },
  "MRO.L":   { name: "Melrose Industries plc", sector: "Industrials" },
  "MTLN.L":  { name: "Mothercare plc", sector: "Retail & Leisure" },
  "NG.L":    { name: "National Grid plc", sector: "Utilities" },
  "NWG.L":   { name: "NatWest Group plc", sector: "Financials" },
  "NXT.L":   { name: "Next plc", sector: "Retail & Leisure" },
  "PCT.L":   { name: "Polar Capital Technology Trust", sector: "Financials" },
  "PRU.L":   { name: "Prudential plc", sector: "Financials" },
  "PSH.L":   { name: "Pershing Square Holdings", sector: "Financials" },
  "PSN.L":   { name: "Persimmon plc", sector: "Real Estate" },
  "PSON.L":  { name: "Pearson plc", sector: "Communication Services" },
  "QQ.L":    { name: "Quintain Estates", sector: "Real Estate" },
  "RDSA.L":  { name: "Shell plc (LSE A)", sector: "Energy – Oil & Gas" },
  "REL.L":   { name: "RELX plc", sector: "Technology" },
  "RIO.L":   { name: "Rio Tinto plc (LSE)", sector: "Materials" },
  "RKT.L":   { name: "Reckitt Benckiser Group plc", sector: "Consumer Staples" },
  "RMV.L":   { name: "Rightmove plc", sector: "Technology" },
  "RR.L":    { name: "Rolls-Royce Holdings plc", sector: "Defense & Aerospace" },
  "RTO.L":   { name: "Rentokil Initial plc", sector: "Industrials" },
  "SBRY.L":  { name: "J Sainsbury plc", sector: "Retail & Leisure" },
  "SDLF.L":  { name: "Sienna SDLF", sector: "Financials" },
  "SDR.L":   { name: "Schroders plc", sector: "Financials" },
  "SGE.L":   { name: "Sage Group plc", sector: "Technology" },
  "SGRO.L":  { name: "SEGRO plc", sector: "Real Estate" },
  "SKY.L":   { name: "Sky plc", sector: "Communication Services" },
  "SMIN.L":  { name: "Smiths Group plc", sector: "Industrials" },
  "SMT.L":   { name: "Scottish Mortgage Investment Trust", sector: "Financials" },
  "SN.L":    { name: "Smith & Nephew plc", sector: "Healthcare" },
  "SPX.L":   { name: "Spirax Group plc", sector: "Industrials" },
  "SSE.L":   { name: "SSE plc", sector: "Utilities" },
  "STAN.L":  { name: "Standard Chartered plc", sector: "Financials" },
  "STJ.L":   { name: "St. James's Place plc", sector: "Financials" },
  "SVT.L":   { name: "Severn Trent plc", sector: "Utilities" },
  "TSCO.L":  { name: "Tesco plc", sector: "Retail & Leisure" },
  "ULVR.L":  { name: "Unilever plc", sector: "Consumer Staples" },
  "UU.L":    { name: "United Utilities Group plc", sector: "Utilities" },
  "VOD.L":   { name: "Vodafone Group plc", sector: "Communication Services" },
  "WEIR.L":  { name: "Weir Group plc", sector: "Industrials" },

  // ══════════════════════════════════════════════════════════════════════════
  // GERMANY (.DE) — XETRA / Frankfurt
  // ══════════════════════════════════════════════════════════════════════════
  "ADS.DE":     { name: "adidas AG", sector: "Retail & Leisure" },
  "AIXA.DE":    { name: "Aixtron SE", sector: "Technology" },
  "BAS.DE":     { name: "BASF SE", sector: "Materials" },
  "BMW.DE":     { name: "BMW AG", sector: "Automotive" },
  "BNR.DE":     { name: "Brenntag SE", sector: "Materials" },
  "BOSS.DE":    { name: "Hugo Boss AG", sector: "Retail & Leisure" },
  "CARL.DE":    { name: "Carl Zeiss Meditec AG", sector: "Healthcare" },
  "CENET.DE":   { name: "Ceconomy AG", sector: "Retail & Leisure" },
  "CON.DE":     { name: "Continental AG", sector: "Automotive" },
  "DB1.DE":     { name: "Deutsche Börse AG", sector: "Financials" },
  "DBK.DE":     { name: "Deutsche Bank AG", sector: "Financials" },
  "DHER.DE":    { name: "Delivery Hero SE", sector: "Technology" },
  "DHL.DE":     { name: "DHL Group", sector: "Industrials" },
  "DKTT.DE":    { name: "Dürr AG", sector: "Industrials" },
  "DWNI.DE":    { name: "Deutsche Wohnen SE", sector: "Real Estate" },
  "EOAN.DE":    { name: "E.ON SE", sector: "Utilities" },
  "EVNT.DE":    { name: "Evotec SE", sector: "Healthcare" },
  "FNTN.DE":    { name: "freenet AG", sector: "Communication Services" },
  "FPH.DE":     { name: "Fielmann Group AG", sector: "Healthcare" },
  "FRE.DE":     { name: "Fresenius SE & Co. KGaA", sector: "Healthcare" },
  "G1A.DE":     { name: "GEA Group AG", sector: "Industrials" },
  "GFT.DE":     { name: "GFT Technologies SE", sector: "Technology" },
  "HEI.DE":     { name: "HeidelbergCement AG", sector: "Materials" },
  "HEN3.DE":    { name: "Henkel AG & Co. KGaA", sector: "Consumer Staples" },
  "HLE.DE":     { name: "Hella GmbH & Co. KGaA", sector: "Automotive" },
  "HOB.DE":     { name: "Hoberg & Driesch Group", sector: "Industrials" },
  "HOT.DE":     { name: "Hypoport SE", sector: "Financials" },
  "IFX.DE":     { name: "Infineon Technologies AG", sector: "Technology" },
  "JEN.DE":     { name: "Jenoptik AG", sector: "Technology" },
  "KGX.DE":     { name: "Kion Group AG", sector: "Industrials" },
  "LEO.DE":     { name: "Leonteq AG", sector: "Financials" },
  "LIN.DE":     { name: "Linde plc (Frankfurt)", sector: "Materials" },
  "LXSG.DE":    { name: "Luxottica Group (Frankfurt)", sector: "Healthcare" },
  "MBG.DE":     { name: "Mercedes-Benz Group AG", sector: "Automotive" },
  "MDG1.DE":    { name: "Medigene AG", sector: "Healthcare" },
  "MLJT.DE":    { name: "Malteser Int.", sector: "Healthcare" },
  "MLP.DE":     { name: "MLP SE", sector: "Financials" },
  "MRK.DE":     { name: "Merck KGaA", sector: "Healthcare" },
  "MTX.DE":     { name: "MTU Aero Engines AG", sector: "Defense & Aerospace" },
  "MUV2.DE":    { name: "Munich Re (Münchener Rück)", sector: "Financials" },
  "NB2.DE":     { name: "Nordex SE", sector: "Clean Energy" },
  "NDA.DE":     { name: "Aurubis AG", sector: "Materials" },
  "NDX1.DE":    { name: "Nordex SE (dup)", sector: "Clean Energy" },
  "P911.DE":    { name: "Porsche AG", sector: "Automotive" },
  "PUM.DE":     { name: "Puma SE", sector: "Retail & Leisure" },
  "QIA.DE":     { name: "Qiagen NV (Frankfurt)", sector: "Healthcare" },
  "RHM.DE":     { name: "Rheinmetall AG", sector: "Defense & Aerospace" },
  "RWE.DE":     { name: "RWE AG", sector: "Utilities" },
  "SHL.DE":     { name: "Siemens Healthineers AG", sector: "Healthcare" },
  "SIEMENS.DE": { name: "Siemens AG", sector: "Industrials" },
  "SRT3.DE":    { name: "Sartorius AG", sector: "Healthcare" },
  "SY1.DE":     { name: "Symrise AG", sector: "Materials" },
  "SZG.DE":     { name: "Salzgitter AG", sector: "Materials" },
  "VNA.DE":     { name: "Vonovia SE", sector: "Real Estate" },
  "VOW3.DE":    { name: "Volkswagen AG", sector: "Automotive" },
  "W8A.DE":     { name: "Westwing Group SE", sector: "Retail & Leisure" },
  "ZAL.DE":     { name: "Zalando SE", sector: "Retail & Leisure" },

  // ══════════════════════════════════════════════════════════════════════════
  // FRANCE (.PA) — Euronext Paris
  // ══════════════════════════════════════════════════════════════════════════
  "ACA.PA":  { name: "Crédit Agricole SA", sector: "Financials" },
  "AI.PA":   { name: "Air Liquide SA", sector: "Materials" },
  "ALO.PA":  { name: "Alstom SA", sector: "Industrials" },
  "ATO.PA":  { name: "Atos SE", sector: "Technology" },
  "AXA.PA":  { name: "AXA SA", sector: "Financials" },
  "BN.PA":   { name: "Danone SA", sector: "Consumer Staples" },
  "CA.PA":   { name: "Carrefour SA", sector: "Retail & Leisure" },
  "CAP.PA":  { name: "Capgemini SE", sector: "Technology" },
  "CS.PA":   { name: "AXA (dup)", sector: "Financials" },
  "DG.PA":   { name: "Vinci SA", sector: "Industrials" },
  "DSY.PA":  { name: "Dassault Systèmes SE", sector: "Technology" },
  "EDEN.PA": { name: "Edenred SE", sector: "Technology" },
  "EL.PA":   { name: "EssilorLuxottica SA", sector: "Healthcare" },
  "EN.PA":   { name: "Bouygues SA", sector: "Industrials" },
  "ERF.PA":  { name: "Eurofins Scientific SE", sector: "Healthcare" },
  "GLE.PA":  { name: "Société Générale SA", sector: "Financials" },
  "HO.PA":   { name: "Thales SA", sector: "Defense & Aerospace" },
  "KER.PA":  { name: "Kering SA", sector: "Retail & Leisure" },
  "LHN.PA":  { name: "Lafarge SA", sector: "Materials" },
  "LR.PA":   { name: "Legrand SA", sector: "Industrials" },
  "LVMH.PA": { name: "LVMH Moët Hennessy Louis Vuitton", sector: "Retail & Leisure" },
  "ML.PA":   { name: "Michelin (CGDE)", sector: "Automotive" },
  "ORA.PA":  { name: "Orange SA", sector: "Communication Services" },
  "PUB.PA":  { name: "Publicis Groupe SA", sector: "Communication Services" },
  "RI.PA":   { name: "Pernod Ricard SA", sector: "Consumer Staples" },
  "RMS.PA":  { name: "Hermès International", sector: "Retail & Leisure" },
  "RNO.PA":  { name: "Renault SA", sector: "Automotive" },
  "SAF.PA":  { name: "Safran SA", sector: "Defense & Aerospace" },
  "SAN.PA":  { name: "Sanofi SA", sector: "Healthcare" },
  "SG.PA":   { name: "Saint-Gobain SA", sector: "Materials" },
  "SGO.PA":  { name: "Saint-Gobain (dup)", sector: "Materials" },
  "STMPA.PA":{ name: "STMicroelectronics NV (Paris)", sector: "Technology" },
  "SU.PA":   { name: "Schneider Electric SE", sector: "Industrials" },
  "VIE.PA":  { name: "Veolia Environnement SA", sector: "Utilities" },
  "VIV.PA":  { name: "Vivendi SE", sector: "Communication Services" },
  "WLN.PA":  { name: "Worldline SA", sector: "Technology" },

  // ══════════════════════════════════════════════════════════════════════════
  // SPAIN (.MC) — Bolsa de Madrid
  // ══════════════════════════════════════════════════════════════════════════
  "ACS.MC":  { name: "ACS Actividades de Construcción", sector: "Industrials" },
  "ACX.MC":  { name: "Acerinox SA", sector: "Materials" },
  "ADV.MC":  { name: "Audax Renovables SA", sector: "Clean Energy" },
  "AENA.MC": { name: "AENA SME SA", sector: "Industrials" },
  "AMS.MC":  { name: "Amadeus IT Group SA", sector: "Technology" },
  "CABK.MC": { name: "CaixaBank SA", sector: "Financials" },
  "CIE.MC":  { name: "CIE Automotive SA", sector: "Automotive" },
  "CLNX.MC": { name: "Cellnex Telecom SA", sector: "Communication Services" },
  "COL.MC":  { name: "Inmobiliaria Colonial SOCIMI SA", sector: "Real Estate" },
  "EDR.MC":  { name: "Edreams Odigeo SA", sector: "Retail & Leisure" },
  "ENG.MC":  { name: "Enagas SA", sector: "Utilities" },
  "FER.MC":  { name: "Ferrovial SE", sector: "Industrials" },
  "GRF.MC":  { name: "Grifols SA", sector: "Healthcare" },
  "IAG.MC":  { name: "International Consolidated Airlines (Madrid)", sector: "Industrials" },
  "IBE.MC":  { name: "Iberdrola SA", sector: "Utilities" },
  "ITX.MC":  { name: "Inditex (Industria de Diseño Textil SA)", sector: "Retail & Leisure" },
  "LOG.MC":  { name: "Logista SA", sector: "Industrials" },
  "MAP.MC":  { name: "Mapfre SA", sector: "Financials" },
  "MEL.MC":  { name: "Meliá Hotels International", sector: "Retail & Leisure" },
  "MRL.MC":  { name: "Merlin Properties SOCIMI SA", sector: "Real Estate" },
  "MTS.MC":  { name: "ArcelorMittal SA (Madrid)", sector: "Materials" },
  "NTGY.MC": { name: "Naturgy Energy Group SA", sector: "Utilities" },
  "PSG.MC":  { name: "Prosegur Cash SA", sector: "Industrials" },
  "RED.MC":  { name: "Red Eléctrica Corp. SA", sector: "Utilities" },
  "REP.MC":  { name: "Repsol SA", sector: "Energy – Oil & Gas" },
  "ROVI.MC": { name: "Laboratorios Farmacéuticos Rovi SA", sector: "Healthcare" },
  "SAB.MC":  { name: "Banco de Sabadell SA", sector: "Financials" },
  "SAN.MC":  { name: "Banco Santander SA", sector: "Financials" },
  "SGRE.MC": { name: "Siemens Gamesa Renewable Energy", sector: "Clean Energy" },
  "SLAB.MC": { name: "Laboratorio Reig Jofre SA", sector: "Healthcare" },
  "SOL.MC":  { name: "Indra Sistemas SA", sector: "Technology" },
  "TEF.MC":  { name: "Telefónica SA", sector: "Communication Services" },
  "UNI.MC":  { name: "Unicaja Banco SA", sector: "Financials" },
  "VIS.MC":  { name: "Viscofan SA", sector: "Consumer Staples" },

  // ══════════════════════════════════════════════════════════════════════════
  // NETHERLANDS (.AS) — Euronext Amsterdam
  // ══════════════════════════════════════════════════════════════════════════
  "ABN.AS":  { name: "ABN AMRO Bank NV", sector: "Financials" },
  "AD.AS":   { name: "Koninklijke Ahold Delhaize NV", sector: "Retail & Leisure" },
  "AKZA.AS": { name: "Akzo Nobel NV", sector: "Materials" },
  "DSM.AS":  { name: "dsm-firmenich AG", sector: "Materials" },
  "EXOR.AS": { name: "Exor NV", sector: "Financials" },
  "GLPG.AS": { name: "Galapagos NV", sector: "Healthcare" },
  "HEIA.AS": { name: "Heineken NV", sector: "Consumer Staples" },
  "IMCD.AS": { name: "IMCD NV", sector: "Materials" },
  "INGA.AS": { name: "ING Groep NV", sector: "Financials" },
  "KPN.AS":  { name: "Koninklijke KPN NV", sector: "Communication Services" },
  "MT.AS":   { name: "ArcelorMittal SA (Amsterdam)", sector: "Materials" },
  "NN.AS":   { name: "NN Group NV", sector: "Financials" },
  "OCI.AS":  { name: "OCI NV", sector: "Materials" },
  "PHIA.AS": { name: "Koninklijke Philips NV", sector: "Healthcare" },
  "PRX.AS":  { name: "Prosus NV", sector: "Technology" },
  "RAND.AS": { name: "Randstad NV", sector: "Industrials" },
  "REN.AS":  { name: "RELX NV (Amsterdam)", sector: "Technology" },
  "SBM.AS":  { name: "SBM Offshore NV", sector: "Energy – Oil & Gas" },
  "SHELL.AS":{ name: "Shell plc (Amsterdam)", sector: "Energy – Oil & Gas" },
  "UNA.AS":  { name: "Unilever plc (Amsterdam)", sector: "Consumer Staples" },
  "URW.AS":  { name: "Unibail-Rodamco-Westfield SE", sector: "Real Estate" },
  "VPK.AS":  { name: "Koninklijke Vopak NV", sector: "Industrials" },
  "WKL.AS":  { name: "Wolters Kluwer NV", sector: "Technology" },
  "YKR.AS":  { name: "Yara International (Amsterdam)", sector: "Materials" },

  // ══════════════════════════════════════════════════════════════════════════
  // SWITZERLAND (.SW) — SIX Swiss Exchange
  // ══════════════════════════════════════════════════════════════════════════
  "ABB.SW":  { name: "ABB Ltd.", sector: "Industrials" },
  "ABBN.SW": { name: "ABB Ltd. (dup)", sector: "Industrials" },
  "ALC.SW":  { name: "Alcon Inc.", sector: "Healthcare" },
  "CFR.SW":  { name: "Compagnie Financière Richemont SA", sector: "Retail & Leisure" },
  "CSGN.SW": { name: "Credit Suisse Group AG", sector: "Financials" },
  "GEBN.SW": { name: "Geberit AG", sector: "Industrials" },
  "GIVN.SW": { name: "Givaudan SA", sector: "Materials" },
  "KNIN.SW": { name: "Kuehne + Nagel International AG", sector: "Industrials" },
  "LOGN.SW": { name: "Logitech International SA", sector: "Technology" },
  "LONN.SW": { name: "Lonza Group AG", sector: "Healthcare" },
  "PGHN.SW": { name: "Partners Group Holding AG", sector: "Financials" },
  "SCMN.SW": { name: "Swisscom AG", sector: "Communication Services" },
  "SIKA.SW": { name: "Sika AG", sector: "Materials" },
  "SLHN.SW": { name: "Swiss Life Holding AG", sector: "Financials" },
  "SRENH.SW":{ name: "Swiss Re AG", sector: "Financials" },
  "UBSG.SW": { name: "UBS Group AG", sector: "Financials" },
  "ZURN.SW": { name: "Zurich Insurance Group AG", sector: "Financials" },

  // ══════════════════════════════════════════════════════════════════════════
  // SWEDEN (.ST) — Nasdaq Stockholm
  // ══════════════════════════════════════════════════════════════════════════
  "ALFA.ST":   { name: "Alfa Laval AB", sector: "Industrials" },
  "ATCO-A.ST": { name: "Atlas Copco AB A", sector: "Industrials" },
  "ERIC-B.ST": { name: "Telefonaktiebolaget LM Ericsson B", sector: "Technology" },
  "ERICB.ST":  { name: "Ericsson B (dup)", sector: "Technology" },
  "EVO.ST":    { name: "Evolution AB", sector: "Retail & Leisure" },
  "HEXA-B.ST": { name: "Hexagon AB B", sector: "Technology" },
  "HUSQ-B.ST": { name: "Husqvarna AB B", sector: "Industrials" },
  "INVE-B.ST": { name: "Investor AB B", sector: "Financials" },
  "SEB-A.ST":  { name: "Skandinaviska Enskilda Banken AB A", sector: "Financials" },
  "SSAB-A.ST": { name: "SSAB AB A", sector: "Materials" },
  "SWED-A.ST": { name: "Swedbank AB A", sector: "Financials" },
  "TEL2-B.ST": { name: "Tele2 AB B", sector: "Communication Services" },
  "TELIA.ST":  { name: "Telia Company AB", sector: "Communication Services" },
  "VOLV-B.ST": { name: "Volvo AB B", sector: "Industrials" },

  // ══════════════════════════════════════════════════════════════════════════
  // ITALY (.MI) — Borsa Italiana
  // ══════════════════════════════════════════════════════════════════════════
  "BAMI.MI": { name: "Banco BPM SpA", sector: "Financials" },
  "CNH.MI":  { name: "CNH Industrial NV", sector: "Industrials" },
  "ENEL.MI": { name: "Enel SpA", sector: "Utilities" },
  "ENI.MI":  { name: "Eni SpA", sector: "Energy – Oil & Gas" },
  "FCA.MI":  { name: "Stellantis NV (Milan)", sector: "Automotive" },
  "G.MI":    { name: "Assicurazioni Generali SpA", sector: "Financials" },
  "ISP.MI":  { name: "Intesa Sanpaolo SpA", sector: "Financials" },
  "MB.MI":   { name: "Mediobanca SpA", sector: "Financials" },
  "MFCM.MI": { name: "MFE-MediaForEurope NV", sector: "Communication Services" },
  "MONC.MI": { name: "Moncler SpA", sector: "Retail & Leisure" },
  "RACE.MI": { name: "Ferrari NV", sector: "Automotive" },
  "REC.MI":  { name: "Recordati SpA", sector: "Healthcare" },
  "STLAM.MI":{ name: "Stellantis NV", sector: "Automotive" },
  "UCG.MI":  { name: "UniCredit SpA", sector: "Financials" },

  // ══════════════════════════════════════════════════════════════════════════
  // DENMARK (.CO) — Nasdaq Copenhagen
  // ══════════════════════════════════════════════════════════════════════════
  "CARL-B.CO": { name: "Carlsberg A/S B", sector: "Consumer Staples" },
  "GN.CO":     { name: "GN Store Nord A/S", sector: "Healthcare" },
  "NETS.CO":   { name: "Nets A/S", sector: "Technology" },
  "NOVO-B.CO": { name: "Novo Nordisk A/S B", sector: "Healthcare" },
  "NZYM-B.CO": { name: "Novozymes A/S B", sector: "Healthcare" },
  "ORSTED.CO": { name: "Ørsted A/S", sector: "Clean Energy" },

  // ══════════════════════════════════════════════════════════════════════════
  // BELGIUM (.BR), IRELAND (.IR), SPECIAL
  // ══════════════════════════════════════════════════════════════════════════
  "ABI.BR":  { name: "Anheuser-Busch InBev SA/NV", sector: "Consumer Staples" },
  "CRH.IR":  { name: "CRH plc", sector: "Materials" },
  "BAM.A":   { name: "Brookfield Asset Management Ltd. A", sector: "Financials" },

  // ══════════════════════════════════════════════════════════════════════════
  // AUSTRALIA (.AX) — Australian Securities Exchange
  // ══════════════════════════════════════════════════════════════════════════
  "AD8.AX":  { name: "Audinate Group Ltd.", sector: "Technology" },
  "AGL.AX":  { name: "AGL Energy Ltd.", sector: "Utilities" },
  "AIS.AX":  { name: "Aeris Resources Ltd.", sector: "Materials" },
  "ALD.AX":  { name: "Ampol Ltd.", sector: "Energy – Oil & Gas" },
  "ALL.AX":  { name: "Aristocrat Leisure Ltd.", sector: "Retail & Leisure" },
  "ALU.AX":  { name: "Altium Ltd.", sector: "Technology" },
  "ALX.AX":  { name: "Atlas Arteria Ltd.", sector: "Industrials" },
  "AMC.AX":  { name: "Amcor plc (ASX)", sector: "Materials" },
  "AMP.AX":  { name: "AMP Ltd.", sector: "Financials" },
  "ANN.AX":  { name: "Ansell Ltd.", sector: "Healthcare" },
  "ANZ.AX":  { name: "Australia and New Zealand Banking Group", sector: "Financials" },
  "APA.AX":  { name: "APA Group", sector: "Utilities" },
  "APX.AX":  { name: "Appen Ltd.", sector: "Technology" },
  "AST.AX":  { name: "AusNet Services Ltd.", sector: "Utilities" },
  "ASX.AX":  { name: "ASX Ltd.", sector: "Financials" },
  "AWC.AX":  { name: "Alumina Ltd.", sector: "Materials" },
  "BHP.AX":  { name: "BHP Group Ltd. (ASX)", sector: "Materials" },
  "BLD.AX":  { name: "Boral Ltd.", sector: "Materials" },
  "BTT.AX":  { name: "BetaShares Global Cybersecurity ETF", sector: "Technology" },
  "CAR.AX":  { name: "CAR Group Ltd.", sector: "Technology" },
  "CBA.AX":  { name: "Commonwealth Bank of Australia", sector: "Financials" },
  "CCX.AX":  { name: "City Chic Collective Ltd.", sector: "Retail & Leisure" },
  "CMW.AX":  { name: "Cromwell Property Group", sector: "Real Estate" },
  "COL.AX":  { name: "Coles Group Ltd.", sector: "Retail & Leisure" },
  "CPU.AX":  { name: "Computershare Ltd.", sector: "Technology" },
  "CSL.AX":  { name: "CSL Ltd.", sector: "Healthcare" },
  "CWN.AX":  { name: "Crown Resorts Ltd.", sector: "Retail & Leisure" },
  "DTL.AX":  { name: "Data#3 Ltd.", sector: "Technology" },
  "DXS.AX":  { name: "Dexus", sector: "Real Estate" },
  "EVN.AX":  { name: "Evolution Mining Ltd.", sector: "Materials" },
  "FMG.AX":  { name: "Fortescue Ltd.", sector: "Materials" },
  "GMG.AX":  { name: "Goodman Group", sector: "Real Estate" },
  "GNC.AX":  { name: "GrainCorp Ltd.", sector: "Consumer Staples" },
  "GOR.AX":  { name: "Gold Road Resources Ltd.", sector: "Materials" },
  "HVN.AX":  { name: "Harvey Norman Holdings Ltd.", sector: "Retail & Leisure" },
  "IAG.AX":  { name: "Insurance Australia Group Ltd.", sector: "Financials" },
  "IEL.AX":  { name: "IDP Education Ltd.", sector: "Retail & Leisure" },
  "IGO.AX":  { name: "IGO Ltd.", sector: "Materials" },
  "IPL.AX":  { name: "Incitec Pivot Ltd.", sector: "Materials" },
  "JBH.AX":  { name: "JB Hi-Fi Ltd.", sector: "Retail & Leisure" },
  "JHX.AX":  { name: "James Hardie Industries plc (ASX)", sector: "Materials" },
  "LLC.AX":  { name: "Lendlease Group", sector: "Real Estate" },
  "LNK.AX":  { name: "Link Administration Holdings Ltd.", sector: "Technology" },
  "LYC.AX":  { name: "Lynas Rare Earths Ltd.", sector: "Materials" },
  "MFG.AX":  { name: "Magellan Financial Group Ltd.", sector: "Financials" },
  "MGR.AX":  { name: "Mirvac Group", sector: "Real Estate" },
  "MIN.AX":  { name: "Mineral Resources Ltd.", sector: "Materials" },
  "MP1.AX":  { name: "Megaport Ltd.", sector: "Technology" },
  "MPL.AX":  { name: "Medibank Private Ltd.", sector: "Healthcare" },
  "MQG.AX":  { name: "Macquarie Group Ltd.", sector: "Financials" },
  "NAB.AX":  { name: "National Australia Bank Ltd.", sector: "Financials" },
  "NCM.AX":  { name: "Newcrest Mining Ltd.", sector: "Materials" },
  "NHF.AX":  { name: "nib Holdings Ltd.", sector: "Healthcare" },
  "NST.AX":  { name: "Northern Star Resources Ltd.", sector: "Materials" },
  "NXT.AX":  { name: "NEXTDC Ltd.", sector: "Technology" },
  "ORG.AX":  { name: "Origin Energy Ltd.", sector: "Energy – Oil & Gas" },
  "ORI.AX":  { name: "Orica Ltd.", sector: "Materials" },
  "OZL.AX":  { name: "OZ Minerals Ltd.", sector: "Materials" },
  "PLS.AX":  { name: "Pilbara Minerals Ltd.", sector: "Materials" },
  "PPT.AX":  { name: "Perpetual Ltd.", sector: "Financials" },
  "PRN.AX":  { name: "Perenti Ltd.", sector: "Materials" },
  "QBE.AX":  { name: "QBE Insurance Group Ltd.", sector: "Financials" },
  "REA.AX":  { name: "REA Group Ltd.", sector: "Technology" },
  "RIO.AX":  { name: "Rio Tinto Ltd. (ASX)", sector: "Materials" },
  "RRL.AX":  { name: "Regis Resources Ltd.", sector: "Materials" },
  "S32.AX":  { name: "South32 Ltd.", sector: "Materials" },
  "SAR.AX":  { name: "Saracen Mineral Holdings Ltd.", sector: "Materials" },
  "SCP.AX":  { name: "SCA Property Group", sector: "Real Estate" },
  "SEK.AX":  { name: "Seek Ltd.", sector: "Technology" },
  "SFR.AX":  { name: "Sandfire Resources Ltd.", sector: "Materials" },
  "SGP.AX":  { name: "Stockland Corp Ltd.", sector: "Real Estate" },
  "SHL.AX":  { name: "Sonic Healthcare Ltd.", sector: "Healthcare" },
  "SKI.AX":  { name: "Spark Infrastructure Group", sector: "Utilities" },
  "STO.AX":  { name: "Santos Ltd.", sector: "Energy – Oil & Gas" },
  "SUN.AX":  { name: "Suncorp Group Ltd.", sector: "Financials" },
  "TAH.AX":  { name: "Tabcorp Holdings Ltd.", sector: "Retail & Leisure" },
  "TCL.AX":  { name: "Transurban Group", sector: "Industrials" },
  "TLS.AX":  { name: "Telstra Group Ltd.", sector: "Communication Services" },
  "TNE.AX":  { name: "Technology One Ltd.", sector: "Technology" },
  "TWE.AX":  { name: "Treasury Wine Estates Ltd.", sector: "Consumer Staples" },
  "VCX.AX":  { name: "Vicinity Centres", sector: "Real Estate" },
  "WBC.AX":  { name: "Westpac Banking Corp.", sector: "Financials" },
  "WES.AX":  { name: "Wesfarmers Ltd.", sector: "Retail & Leisure" },
  "WOW.AX":  { name: "Woolworths Group Ltd.", sector: "Retail & Leisure" },
  "WPL.AX":  { name: "Woodside Energy Group Ltd.", sector: "Energy – Oil & Gas" },
  "WSA.AX":  { name: "Western Areas Ltd.", sector: "Materials" },
  "WTC.AX":  { name: "WiseTech Global Ltd.", sector: "Technology" },
  "XRO.AX":  { name: "Xero Ltd.", sector: "Technology" },

  // ══════════════════════════════════════════════════════════════════════════
  // INDIA (.NS) — NSE India
  // ══════════════════════════════════════════════════════════════════════════
  "ADANIPORTS.NS": { name: "Adani Ports and Special Economic Zone Ltd.", sector: "Industrials" },
  "ASIANPAINT.NS": { name: "Asian Paints Ltd.", sector: "Materials" },
  "AXISBANK.NS":   { name: "Axis Bank Ltd.", sector: "Financials" },
  "BAJFINANCE.NS": { name: "Bajaj Finance Ltd.", sector: "Financials" },
  "BHARTIARTL.NS": { name: "Bharti Airtel Ltd.", sector: "Communication Services" },
  "HCLTECH.NS":    { name: "HCL Technologies Ltd.", sector: "Technology" },
  "HDFCBANK.NS":   { name: "HDFC Bank Ltd.", sector: "Financials" },
  "ICICIBANK.NS":  { name: "ICICI Bank Ltd.", sector: "Financials" },
  "INFY.NS":       { name: "Infosys Ltd.", sector: "Technology" },
  "ITC.NS":        { name: "ITC Ltd.", sector: "Consumer Staples" },
  "JSWSTEEL.NS":   { name: "JSW Steel Ltd.", sector: "Materials" },
  "KOTAKBANK.NS":  { name: "Kotak Mahindra Bank Ltd.", sector: "Financials" },
  "LT.NS":         { name: "Larsen & Toubro Ltd.", sector: "Industrials" },
  "M&M.NS":        { name: "Mahindra & Mahindra Ltd.", sector: "Automotive" },
  "MARUTI.NS":     { name: "Maruti Suzuki India Ltd.", sector: "Automotive" },
  "NESTLEIND.NS":  { name: "Nestlé India Ltd.", sector: "Consumer Staples" },
  "NTPC.NS":       { name: "NTPC Ltd.", sector: "Utilities" },
  "ONGC.NS":       { name: "Oil and Natural Gas Corp. Ltd.", sector: "Energy – Oil & Gas" },
  "POWERGRID.NS":  { name: "Power Grid Corp. of India Ltd.", sector: "Utilities" },
  "RELIANCE.NS":   { name: "Reliance Industries Ltd.", sector: "Energy – Oil & Gas" },
  "SBIN.NS":       { name: "State Bank of India", sector: "Financials" },
  "SUNPHARMA.NS":  { name: "Sun Pharmaceutical Industries Ltd.", sector: "Healthcare" },
  "TATASTEEL.NS":  { name: "Tata Steel Ltd.", sector: "Materials" },
  "TCS.NS":        { name: "Tata Consultancy Services Ltd.", sector: "Technology" },
  "TITAN.NS":      { name: "Titan Company Ltd.", sector: "Retail & Leisure" },
  "ULTRACEMCO.NS": { name: "UltraTech Cement Ltd.", sector: "Materials" },
  "WIPRO.NS":      { name: "Wipro Ltd.", sector: "Technology" },

  // ══════════════════════════════════════════════════════════════════════════
  // US TICKERS (still in Other — bare name, no Yahoo sector returned)
  // Sorted A–Z. Mix of mid-cap and small-cap US stocks.
  // ══════════════════════════════════════════════════════════════════════════
  "ABCB":   { name: "Ameris Bancorp", sector: "Financials" },
  "ABM":    { name: "ABM Industries Inc.", sector: "Industrials" },
  "ACCD":   { name: "Accolade Inc.", sector: "Healthcare" },
  "ACDC":   { name: "ProFrac Holding Corp.", sector: "Energy – Oil & Gas" },
  "ACHC":   { name: "Acadia Healthcare Co.", sector: "Healthcare" },
  "ACHR":   { name: "Archer Aviation Inc.", sector: "Industrials" },
  "ACI":    { name: "Albertsons Companies Inc.", sector: "Retail & Leisure" },
  "ACM":    { name: "AECOM", sector: "Industrials" },
  "ACNB":   { name: "ACNB Corp.", sector: "Financials" },
  "ACVA":   { name: "ACV Auctions Inc.", sector: "Technology" },
  "ACXM":   { name: "Acxiom Corp.", sector: "Technology" },
  "ADNT":   { name: "Adient plc", sector: "Automotive" },
  "ADUS":   { name: "Addus HomeCare Corp.", sector: "Healthcare" },
  "AEYE":   { name: "AudioEye Inc.", sector: "Technology" },
  "AFRM":   { name: "Affirm Holdings Inc.", sector: "Financials" },
  "AFT":    { name: "Apollo Senior Floating Rate Fund", sector: "Financials" },
  "AFYA":   { name: "Afya Ltd.", sector: "Healthcare" },
  "AGCO":   { name: "AGCO Corp.", sector: "Industrials" },
  "AGS":    { name: "PlayAGS Inc.", sector: "Retail & Leisure" },
  "AGYS":   { name: "Agilysys Inc.", sector: "Technology" },
  "AHH":    { name: "Armada Hoffler Properties", sector: "Real Estate" },
  "AHPI":   { name: "Allied Healthcare Products Inc.", sector: "Healthcare" },
  "AIN":    { name: "Albany International Corp.", sector: "Industrials" },
  "AIT":    { name: "Applied Industrial Technologies", sector: "Industrials" },
  "AIXI":   { name: "Xin Guang Jian International", sector: "Technology" },
  "AKBA":   { name: "Akebia Therapeutics Inc.", sector: "Healthcare" },
  "AKTX":   { name: "Akeso Inc.", sector: "Healthcare" },
  "ALCO":   { name: "Alico Inc.", sector: "Consumer Staples" },
  "ALDX":   { name: "Aldeyra Therapeutics Inc.", sector: "Healthcare" },
  "ALE":    { name: "ALLETE Inc.", sector: "Utilities" },
  "ALG":    { name: "Alamo Group Inc.", sector: "Industrials" },
  "ALGT":   { name: "Allegiant Travel Co.", sector: "Industrials" },
  "ALHC":   { name: "Alignment Healthcare Inc.", sector: "Healthcare" },
  "ALIM":   { name: "Alimera Sciences Inc.", sector: "Healthcare" },
  "ALIT":   { name: "Alight Inc.", sector: "Technology" },
  "ALKS":   { name: "Alkermes plc", sector: "Healthcare" },
  "ALRM":   { name: "Alarm.com Holdings Inc.", sector: "Technology" },
  "ALSA":   { name: "Alpha Star Acquisition Corp.", sector: "Financials" },
  "ALT":    { name: "Altimmune Inc.", sector: "Healthcare" },
  "ALTR":   { name: "Altair Engineering Inc.", sector: "Technology" },
  "ALVR":   { name: "AlloVir Inc.", sector: "Healthcare" },
  "AMAG":   { name: "AMAG Pharmaceuticals Inc.", sector: "Healthcare" },
  "AMBC":   { name: "Ambac Financial Group Inc.", sector: "Financials" },
  "AMEH":   { name: "Apollo Medical Holdings Inc.", sector: "Healthcare" },
  "AMFT":   { name: "Amplify ETF Trust", sector: "Financials" },
  "AMG":    { name: "Affiliated Managers Group Inc.", sector: "Financials" },
  "AMKR":   { name: "Amkor Technology Inc.", sector: "Technology" },
  "AMN":    { name: "AMN Healthcare Services Inc.", sector: "Healthcare" },
  "AMOD":   { name: "A-Mode Inc.", sector: "Technology" },
  "AMPE":   { name: "Ampio Pharmaceuticals Inc.", sector: "Healthcare" },
  "AMPY":   { name: "Amplify Energy Corp.", sector: "Energy – Oil & Gas" },
  "AMRC":   { name: "Ameresco Inc.", sector: "Clean Energy" },
  "AMRK":   { name: "A-Mark Precious Metals Inc.", sector: "Materials" },
  "AMRN":   { name: "Amarin Corp. plc", sector: "Healthcare" },
  "AMRS":   { name: "Amyris Inc.", sector: "Healthcare" },
  "AMSC":   { name: "American Superconductor Corp.", sector: "Industrials" },
  "AMTD":   { name: "AMTD Digital Inc.", sector: "Financials" },
  "AMWD":   { name: "American Woodmark Corp.", sector: "Industrials" },
  "AMWL":   { name: "American Well Corp.", sector: "Healthcare" },
  "ANF":    { name: "Abercrombie & Fitch Co.", sector: "Retail & Leisure" },
  "ANGI":   { name: "Angi Inc.", sector: "Technology" },
  "ANIX":   { name: "Anixa Biosciences Inc.", sector: "Healthcare" },
  "ANY":    { name: "Sphere 3D Corp.", sector: "Technology" },
  "APOG":   { name: "Apogee Enterprises Inc.", sector: "Industrials" },
  "APPH":   { name: "AppHarvest Inc.", sector: "Consumer Staples" },
  "APRE":   { name: "Aprea Therapeutics Inc.", sector: "Healthcare" },
  "APRL":   { name: "April Skincare", sector: "Consumer Staples" },
  "APWC":   { name: "Asia Pacific Wire & Cable Corp.", sector: "Industrials" },
  "AQB":    { name: "AquaBounty Technologies Inc.", sector: "Consumer Staples" },
  "AQMS":   { name: "Aqua Metals Inc.", sector: "Materials" },
  "ARCB":   { name: "ArcBest Corp.", sector: "Industrials" },
  "ARCC":   { name: "Ares Capital Corp.", sector: "Financials" },
  "ARCH":   { name: "Arch Resources Inc.", sector: "Materials" },
  "ARCO":   { name: "Arcos Dorados Holdings Inc.", sector: "Retail & Leisure" },
  "ARCX":   { name: "Arc Terminals Holdings LLC", sector: "Energy – Oil & Gas" },
  "ARDX":   { name: "Ardelyx Inc.", sector: "Healthcare" },
  "AREC":   { name: "American Resources Corp.", sector: "Materials" },
  "ARI":    { name: "Apollo Commercial Real Estate Finance", sector: "Real Estate" },
  "ARKO":   { name: "ARKO Corp.", sector: "Retail & Leisure" },
  "ARMP":   { name: "Armata Pharmaceuticals Inc.", sector: "Healthcare" },
  "ARQT":   { name: "Arcutis Biotherapeutics Inc.", sector: "Healthcare" },
  "ARRY":   { name: "Array Technologies Inc.", sector: "Clean Energy" },
  "ARTNA":  { name: "Artesian Resources Corp.", sector: "Utilities" },
  "ARTW":   { name: "Art's-Way Manufacturing Co.", sector: "Industrials" },
  "ARW":    { name: "Arrow Electronics Inc.", sector: "Technology" },
  "ARWR":   { name: "Arrowhead Pharmaceuticals Inc.", sector: "Healthcare" },
  "ASA":    { name: "ASA Gold and Precious Metals", sector: "Materials" },
  "ASAI":   { name: "Sendas Distribuidora SA", sector: "Retail & Leisure" },
  "ASAN":   { name: "Asana Inc.", sector: "Technology" },
  "ASB":    { name: "Associated Banc-Corp", sector: "Financials" },
  "ASEL":   { name: "Aselsan Elektronik Sanayi", sector: "Defense & Aerospace" },
  "ASGN":   { name: "ASGN Inc.", sector: "Technology" },
  "ASH":    { name: "Ashland Inc.", sector: "Materials" },
  "ASIX":   { name: "AdvanSix Inc.", sector: "Materials" },
  "ASLN":   { name: "ASLAN Pharmaceuticals Ltd.", sector: "Healthcare" },
  "ASO":    { name: "Academy Sports and Outdoors Inc.", sector: "Retail & Leisure" },
  "ASPI":   { name: "ASP Isotopes Inc.", sector: "Materials" },
  "ASPN":   { name: "Aspen Aerogels Inc.", sector: "Industrials" },
  "ASTE":   { name: "Astec Industries Inc.", sector: "Industrials" },
  "ASTL":   { name: "Algoma Steel Group Inc.", sector: "Materials" },
  "ASTR":   { name: "Astra Space Inc.", sector: "Industrials" },
  "ASUR":   { name: "Asure Software Inc.", sector: "Technology" },
  "ATAI":   { name: "atai Life Sciences NV", sector: "Healthcare" },
  "ATAX":   { name: "America First Multifamily Investors LP", sector: "Real Estate" },
  "ATEX":   { name: "Anterix Inc.", sector: "Communication Services" },
  "ATH":    { name: "Athene Holding Ltd.", sector: "Financials" },
  "ATKR":   { name: "Atkore Inc.", sector: "Industrials" },
  "ATLO":   { name: "Ames National Corp.", sector: "Financials" },
  "ATRC":   { name: "AtriCure Inc.", sector: "Healthcare" },
  "ATUS":   { name: "Altice USA Inc.", sector: "Communication Services" },
  "AUB":    { name: "Atlantic Union Bankshares Corp.", sector: "Financials" },
  "AUBN":   { name: "Auburn National Bancorporation", sector: "Financials" },
  "AUG":    { name: "Augmedix Inc.", sector: "Healthcare" },
  "AUGX":   { name: "Augmedix Inc. (dup)", sector: "Healthcare" },
  "AUID":   { name: "authID Inc.", sector: "Technology" },
  "AUMN":   { name: "Golden Minerals Co.", sector: "Materials" },
  "AUPH":   { name: "Aurinia Pharmaceuticals Inc.", sector: "Healthcare" },
  "AVAH":   { name: "Aveanna Healthcare Holdings Inc.", sector: "Healthcare" },
  "AVAV":   { name: "AeroVironment Inc.", sector: "Defense & Aerospace" },
  "AVBH":   { name: "Avidbank Holdings Inc.", sector: "Financials" },
  "AVCO":   { name: "Avalon GloboCare Corp.", sector: "Healthcare" },
  "AVGR":   { name: "Avinger Inc.", sector: "Healthcare" },
  "AVHI":   { name: "Aviation Holdings Inc.", sector: "Industrials" },
  "AVID":   { name: "Avid Technology Inc.", sector: "Technology" },
  "AVNW":   { name: "Aviat Networks Inc.", sector: "Technology" },
  "AVPT":   { name: "AvePoint Inc.", sector: "Technology" },
  "AVT":    { name: "Avnet Inc.", sector: "Technology" },
  "AWR":    { name: "American States Water Co.", sector: "Utilities" },
  "AXDX":   { name: "Accelerate Diagnostics Inc.", sector: "Healthcare" },
  "AXL":    { name: "American Axle & Manufacturing Holdings", sector: "Automotive" },
  "AXNX":   { name: "Axonics Inc.", sector: "Healthcare" },
  "AXS":    { name: "AXIS Capital Holdings Ltd.", sector: "Financials" },
  "AXTI":   { name: "AXT Inc.", sector: "Technology" },
  "AYI":    { name: "Acuity Brands Inc.", sector: "Industrials" },
  "AZTA":   { name: "Azenta Inc.", sector: "Technology" },
  "AZZ":    { name: "AZZ Inc.", sector: "Industrials" },
  "BABA":   { name: "Alibaba Group Holding Ltd.", sector: "Technology" },
  "BAM":    { name: "Brookfield Asset Management Ltd.", sector: "Financials" },
  "BAND":   { name: "Bandwidth Inc.", sector: "Technology" },
  "BANF":   { name: "BancFirst Corp.", sector: "Financials" },
  "BANR":   { name: "Banner Financial Corp.", sector: "Financials" },
  "BATRA":  { name: "Liberty Media Corp. (Series A)", sector: "Communication Services" },
  "BBD":    { name: "Banco Bradesco SA", sector: "Financials" },
  "BCO":    { name: "Brink's Co.", sector: "Industrials" },
  "BEAM":   { name: "Beam Therapeutics Inc.", sector: "Healthcare" },
  "BEEM":   { name: "Beam Global Inc.", sector: "Clean Energy" },
  "BEKE":   { name: "KE Holdings Inc.", sector: "Real Estate" },
  "BFAM":   { name: "Bright Horizons Family Solutions", sector: "Healthcare" },
  "BGS":    { name: "B&G Foods Inc.", sector: "Consumer Staples" },
  "BIDU":   { name: "Baidu Inc.", sector: "Technology" },
  "BILI":   { name: "Bilibili Inc.", sector: "Technology" },
  "BIRD":   { name: "Allbirds Inc.", sector: "Retail & Leisure" },
  "BITF":   { name: "Bitfarms Ltd.", sector: "Crypto & Digital Assets" },
  "BJ":     { name: "BJ's Wholesale Club Holdings", sector: "Retail & Leisure" },
  "BKE":    { name: "Buckle Inc.", sector: "Retail & Leisure" },
  "BKH":    { name: "Black Hills Corp.", sector: "Utilities" },
  "BLFQ":   { name: "Balqon Corp.", sector: "Industrials" },
  "BLNK":   { name: "Blink Charging Co.", sector: "Clean Energy" },
  "BLUE":   { name: "bluebird bio Inc.", sector: "Healthcare" },
  "BN":     { name: "Brookfield Corp.", sector: "Financials" },
  "BNS":    { name: "Bank of Nova Scotia", sector: "Financials" },
  "BOX":    { name: "Box Inc.", sector: "Technology" },
  "BRC":    { name: "Brady Corp.", sector: "Industrials" },
  "BRFS":   { name: "BRF SA", sector: "Consumer Staples" },
  "BRKR":   { name: "Bruker Corp.", sector: "Technology" },
  "BTBT":   { name: "Bit Brother Ltd.", sector: "Crypto & Digital Assets" },
  "BURL":   { name: "Burlington Stores Inc.", sector: "Retail & Leisure" },
  "BVS":    { name: "Bioventus Inc.", sector: "Healthcare" },
  "BWA":    { name: "BorgWarner Inc.", sector: "Automotive" },
  "BXSL":   { name: "Blackstone Secured Lending Fund", sector: "Financials" },
  "CALM":   { name: "Cal-Maine Foods Inc.", sector: "Consumer Staples" },
  "CANO":   { name: "Cano Health Inc.", sector: "Healthcare" },
  "CARA":   { name: "Cara Therapeutics Inc.", sector: "Healthcare" },
  "CBSH":   { name: "Commerce Bancshares Inc.", sector: "Financials" },
  "CBTX":   { name: "CBTX Inc.", sector: "Financials" },
  "CC":     { name: "Chemours Co.", sector: "Materials" },
  "CCCS":   { name: "CCC Intelligent Solutions Holdings", sector: "Technology" },
  "CCEP":   { name: "Coca-Cola Europacific Partners plc", sector: "Consumer Staples" },
  "CCF":    { name: "Chase Corp.", sector: "Industrials" },
  "CCOI":   { name: "Cogent Communications Holdings", sector: "Communication Services" },
  "CCRN":   { name: "Cross Country Healthcare Inc.", sector: "Healthcare" },
  "CDAK":   { name: "Codiak BioSciences Inc.", sector: "Healthcare" },
  "CDAY":   { name: "Ceridian HCM Holding Inc.", sector: "Technology" },
  "CDRE":   { name: "Cadre Holdings Inc.", sector: "Defense & Aerospace" },
  "CDT":    { name: "Conduit Pharmaceuticals Inc.", sector: "Healthcare" },
  "CECO":   { name: "CECO Environmental Corp.", sector: "Industrials" },
  "CEIX":   { name: "CONSOL Energy Inc.", sector: "Energy – Oil & Gas" },
  "CELH":   { name: "Celsius Holdings Inc.", sector: "Consumer Staples" },
  "CENT":   { name: "Central Garden and Pet Co.", sector: "Consumer Staples" },
  "CENTA":  { name: "Central Garden and Pet Co. A", sector: "Consumer Staples" },
  "CENX":   { name: "Century Aluminum Co.", sector: "Materials" },
  "CEPH":   { name: "Cephalon Inc.", sector: "Healthcare" },
  "CERT":   { name: "Certara Inc.", sector: "Healthcare" },
  "CEVA":   { name: "CEVA Inc.", sector: "Technology" },
  "CFB":    { name: "CrossFirst Bankshares Inc.", sector: "Financials" },
  "CFBK":   { name: "CF Bankshares Inc.", sector: "Financials" },
  "CFFI":   { name: "C&F Financial Corp.", sector: "Financials" },
  "CFFN":   { name: "Capitol Federal Financial Inc.", sector: "Financials" },
  "CFLT":   { name: "Confluent Inc.", sector: "Technology" },
  "CFR":    { name: "Cullen/Frost Bankers Inc.", sector: "Financials" },
  "CFSB":   { name: "CFSB Bancorp Inc.", sector: "Financials" },
  "CG":     { name: "Carlyle Group Inc.", sector: "Financials" },
  "CHE":    { name: "Chemed Corp.", sector: "Healthcare" },
  "CHH":    { name: "Choice Hotels International Inc.", sector: "Retail & Leisure" },
  "CHPT":   { name: "ChargePoint Holdings Inc.", sector: "Clean Energy" },
  "CHX":    { name: "ChampionX Corp.", sector: "Energy – Oil & Gas" },
  "CIFR":   { name: "Cipher Mining Inc.", sector: "Crypto & Digital Assets" },
  "CIFS":   { name: "China Index Holdings Ltd.", sector: "Real Estate" },
  "CLFD":   { name: "Clearfield Inc.", sector: "Technology" },
  "CLOV":   { name: "Clover Health Investments Corp.", sector: "Healthcare" },
  "CLSK":   { name: "CleanSpark Inc.", sector: "Crypto & Digital Assets" },
  "CMD":    { name: "Cantel Medical Corp.", sector: "Healthcare" },
  "CMP":    { name: "Compass Minerals International", sector: "Materials" },
  "CNMD":   { name: "CONMED Corp.", sector: "Healthcare" },
  "CNO":    { name: "CNO Financial Group Inc.", sector: "Financials" },
  "CNXN":   { name: "PC Connection Inc.", sector: "Technology" },
  "COLD":   { name: "Americold Realty Trust Inc.", sector: "Real Estate" },
  "CONE":   { name: "CyrusOne Inc.", sector: "Real Estate" },
  "CPA":    { name: "Copa Holdings SA", sector: "Industrials" },
  "CPK":    { name: "Chesapeake Utilities Corp.", sector: "Utilities" },
  "CPRX":   { name: "Catalyst Biosciences Inc.", sector: "Healthcare" },
  "CROX":   { name: "Crocs Inc.", sector: "Retail & Leisure" },
  "CRSP":   { name: "CRISPR Therapeutics AG", sector: "Healthcare" },
  "CSL":    { name: "Carlisle Companies Inc.", sector: "Industrials" },
  "CSWI":   { name: "CSW Industrials Inc.", sector: "Industrials" },
  "CTLP":   { name: "Cantaloupe Inc.", sector: "Technology" },
  "CUBE":   { name: "CubeSmart", sector: "Real Estate" },
  "CUZ":    { name: "Cousins Properties Inc.", sector: "Real Estate" },
  "CVBF":   { name: "CVB Financial Corp.", sector: "Financials" },
  "CWST":   { name: "Casella Waste Systems Inc.", sector: "Industrials" },
  "CWT":    { name: "California Water Service Group", sector: "Utilities" },
  "DBRG":   { name: "DigitalBridge Group Inc.", sector: "Real Estate" },
  "DGII":   { name: "Digi International Inc.", sector: "Technology" },
  "DICE":   { name: "DICE Therapeutics Inc.", sector: "Healthcare" },
  "DNB":    { name: "Dun & Bradstreet Holdings Inc.", sector: "Technology" },
  "DOCN":   { name: "DigitalOcean Holdings Inc.", sector: "Technology" },
  "DOCS":   { name: "Doximity Inc.", sector: "Healthcare" },
  "DOMO":   { name: "Domo Inc.", sector: "Technology" },
  "DRVN":   { name: "Driven Brands Holdings Inc.", sector: "Retail & Leisure" },
  "DSGR":   { name: "Distribution Solutions Group Inc.", sector: "Industrials" },
  "DXPE":   { name: "DXP Enterprises Inc.", sector: "Industrials" },
  "EBIX":   { name: "Ebix Inc.", sector: "Technology" },
  "EDIT":   { name: "Editas Medicine Inc.", sector: "Healthcare" },
  "EDU":    { name: "New Oriental Education & Technology", sector: "Retail & Leisure" },
  "EFC":    { name: "Ellington Financial Inc.", sector: "Financials" },
  "EFSC":   { name: "Enterprise Financial Services Corp.", sector: "Financials" },
  "EGBN":   { name: "Eagle Bancorp Inc.", sector: "Financials" },
  "EHC":    { name: "Encompass Health Corp.", sector: "Healthcare" },
  "ELME":   { name: "Elme Communities", sector: "Real Estate" },
  "EMKR":   { name: "EMCORE Corp.", sector: "Technology" },
  "ENOV":   { name: "Enovis Corp.", sector: "Healthcare" },
  "ENPH":   { name: "Enphase Energy Inc.", sector: "Clean Energy" },
  "ENSG":   { name: "Ensign Group Inc.", sector: "Healthcare" },
  "ENV":    { name: "Envestnet Inc.", sector: "Technology" },
  "EPPW":   { name: "EP Energy Corp.", sector: "Energy – Oil & Gas" },
  "EPRT":   { name: "Essential Properties Realty Trust", sector: "Real Estate" },
  "ETWO":   { name: "E2open Parent Holdings Inc.", sector: "Technology" },
  "EVBG":   { name: "Everbridge Inc.", sector: "Technology" },
  "EVERI":  { name: "Everi Holdings Inc.", sector: "Technology" },
  "EVGO":   { name: "EVgo Inc.", sector: "Clean Energy" },
  "EXEL":   { name: "Exelixis Inc.", sector: "Healthcare" },
  "EXP":    { name: "Eagle Materials Inc.", sector: "Materials" },
  "EXPO":   { name: "Exponent Inc.", sector: "Technology" },
  "EYE":    { name: "National Vision Holdings Inc.", sector: "Healthcare" },
  "FATE":   { name: "Fate Therapeutics Inc.", sector: "Healthcare" },
  "FCEL":   { name: "FuelCell Energy Inc.", sector: "Clean Energy" },
  "FCN":    { name: "FTI Consulting Inc.", sector: "Industrials" },
  "FGEN":   { name: "FibroGen Inc.", sector: "Healthcare" },
  "FHI":    { name: "Federated Hermes Inc.", sector: "Financials" },
  "FIGS":   { name: "FIGS Inc.", sector: "Retail & Leisure" },
  "FINV":   { name: "FinVolution Group", sector: "Financials" },
  "FLO":    { name: "Flowers Foods Inc.", sector: "Consumer Staples" },
  "FOLD":   { name: "Amicus Therapeutics Inc.", sector: "Healthcare" },
  "FORM":   { name: "FormFactor Inc.", sector: "Technology" },
  "FR":     { name: "First Industrial Realty Trust", sector: "Real Estate" },
  "FRSH":   { name: "Freshworks Inc.", sector: "Technology" },
  "FUL":    { name: "H.B. Fuller Co.", sector: "Materials" },
  "GAIN":   { name: "Gladstone Investment Corp.", sector: "Financials" },
  "GAN":    { name: "GAN Ltd.", sector: "Technology" },
  "GARTNER":{ name: "Gartner Inc.", sector: "Technology" },
  "GBDC":   { name: "Golub Capital BDC Inc.", sector: "Financials" },
  "GCO":    { name: "Genesco Inc.", sector: "Retail & Leisure" },
  "GEVO":   { name: "Gevo Inc.", sector: "Clean Energy" },
  "GFF":    { name: "Griffon Corp.", sector: "Industrials" },
  "GHC":    { name: "Graham Holdings Co.", sector: "Communication Services" },
  "GIII":   { name: "G-III Apparel Group Ltd.", sector: "Retail & Leisure" },
  "GLDD":   { name: "Great Lakes Dredge & Dock Corp.", sector: "Industrials" },
  "GMS":    { name: "GMS Inc.", sector: "Industrials" },
  "GNSS":   { name: "Genasys Inc.", sector: "Technology" },
  "GNTX":   { name: "Gentex Corp.", sector: "Automotive" },
  "GOTU":   { name: "Gaotu Techedu Inc.", sector: "Technology" },
  "GOX":    { name: "Genie Energy Ltd.", sector: "Utilities" },
  "GPI":    { name: "Group 1 Automotive Inc.", sector: "Retail & Leisure" },
  "GPRE":   { name: "Green Plains Inc.", sector: "Energy – Oil & Gas" },
  "GRAB":   { name: "Grab Holdings Ltd.", sector: "Technology" },
  "GRAY":   { name: "Gray Television Inc.", sector: "Communication Services" },
  "GRPN":   { name: "Groupon Inc.", sector: "Retail & Leisure" },
  "GSHD":   { name: "Goosehead Insurance Inc.", sector: "Financials" },
  "GTY":    { name: "Getty Realty Corp.", sector: "Real Estate" },
  "HAE":    { name: "Haemonetics Corp.", sector: "Healthcare" },
  "HAFC":   { name: "Hanmi Financial Corp.", sector: "Financials" },
  "HALO":   { name: "Halozyme Therapeutics Inc.", sector: "Healthcare" },
  "HAYW":   { name: "Hayward Holdings Inc.", sector: "Industrials" },
  "HBI":    { name: "Hanesbrands Inc.", sector: "Retail & Leisure" },
  "HBT":    { name: "HBT Financial Inc.", sector: "Financials" },
  "HCKT":   { name: "Hackett Group Inc.", sector: "Technology" },
  "HGV":    { name: "Hilton Grand Vacations Inc.", sector: "Retail & Leisure" },
  "HIW":    { name: "Highwoods Properties Inc.", sector: "Real Estate" },
  "HLF":    { name: "Herbalife Ltd.", sector: "Consumer Staples" },
  "HLNE":   { name: "Hamilton Lane Inc.", sector: "Financials" },
  "HMN":    { name: "Horace Mann Educators Corp.", sector: "Financials" },
  "HMST":   { name: "HomeStreet Inc.", sector: "Financials" },
  "HNI":    { name: "HNI Corp.", sector: "Industrials" },
  "HPK":    { name: "HighPeak Energy Inc.", sector: "Energy – Oil & Gas" },
  "HRMY":   { name: "Harmony Biosciences Holdings Inc.", sector: "Healthcare" },
  "HTGC":   { name: "Hercules Capital Inc.", sector: "Financials" },
  "HTLF":   { name: "Heartland Financial USA Inc.", sector: "Financials" },
  "HURN":   { name: "Huron Consulting Group Inc.", sector: "Industrials" },
  "HUT8":   { name: "Hut 8 Corp.", sector: "Crypto & Digital Assets" },
  "IBP":    { name: "Installed Building Products Inc.", sector: "Industrials" },
  "ICAD":   { name: "iCAD Inc.", sector: "Healthcare" },
  "ICUI":   { name: "ICU Medical Inc.", sector: "Healthcare" },
  "IDCC":   { name: "InterDigital Inc.", sector: "Technology" },
  "IIIN":   { name: "Insteel Industries Inc.", sector: "Materials" },
  "IIPR":   { name: "Innovative Industrial Properties Inc.", sector: "Real Estate" },
  "INFY":   { name: "Infosys Ltd. (US ADR)", sector: "Technology" },
  "INMD":   { name: "InMode Ltd.", sector: "Healthcare" },
  "INN":    { name: "Summit Hotel Properties Inc.", sector: "Real Estate" },
  "INSP":   { name: "Inspire Medical Systems Inc.", sector: "Healthcare" },
  "INVA":   { name: "Innoviva Inc.", sector: "Healthcare" },
  "IONS":   { name: "Ionis Pharmaceuticals Inc.", sector: "Healthcare" },
  "IQ":     { name: "iQIYI Inc.", sector: "Technology" },
  "IRDM":   { name: "Iridium Communications Inc.", sector: "Communication Services" },
  "ITGR":   { name: "Integer Holdings Corp.", sector: "Healthcare" },
  "ITUB":   { name: "Itaú Unibanco Holding SA", sector: "Financials" },
  "JD":     { name: "JD.com Inc.", sector: "Retail & Leisure" },
  "JOBY":   { name: "Joby Aviation Inc.", sector: "Industrials" },
  "KPTI":   { name: "Karyopharm Therapeutics Inc.", sector: "Healthcare" },
  "KRTX":   { name: "Karuna Therapeutics Inc.", sector: "Healthcare" },
  "KRYS":   { name: "Krystal Biotech Inc.", sector: "Healthcare" },
  "LAIX":   { name: "LAIX Inc.", sector: "Technology" },
  "LCID":   { name: "Lucid Group Inc.", sector: "Automotive" },
  "LI":     { name: "Li Auto Inc.", sector: "Automotive" },
  "LILM":   { name: "Lilium NV", sector: "Industrials" },
  "LIVN":   { name: "LivaNova plc", sector: "Healthcare" },
  "LMND":   { name: "Lemonade Inc.", sector: "Financials" },
  "LSI":    { name: "Life Storage Inc.", sector: "Real Estate" },
  "LUMN":   { name: "Lumen Technologies Inc.", sector: "Communication Services" },
  "MAIN":   { name: "Main Street Capital Corp.", sector: "Financials" },
  "MARA":   { name: "Marathon Digital Holdings Inc.", sector: "Crypto & Digital Assets" },
  "MASI":   { name: "Masimo Corp.", sector: "Healthcare" },
  "MDXG":   { name: "MiMedx Group Inc.", sector: "Healthcare" },
  "MELI":   { name: "MercadoLibre Inc.", sector: "Technology" },
  "MGNX":   { name: "MacroGenics Inc.", sector: "Healthcare" },
  "MOV":    { name: "Movado Group Inc.", sector: "Retail & Leisure" },
  "NCNO":   { name: "nCino Inc.", sector: "Technology" },
  "NET":    { name: "Cloudflare Inc.", sector: "Technology" },
  "NEWT":   { name: "NewtekOne Inc.", sector: "Financials" },
  "NIO":    { name: "NIO Inc.", sector: "Automotive" },
  "NOVA":   { name: "Sunnova Energy International Inc.", sector: "Clean Energy" },
  "NSA":    { name: "National Storage Affiliates Trust", sector: "Real Estate" },
  "NTES":   { name: "NetEase Inc.", sector: "Technology" },
  "NTLA":   { name: "Intellia Therapeutics Inc.", sector: "Healthcare" },
  "NU":     { name: "Nu Holdings Ltd.", sector: "Financials" },
  "NUVL":   { name: "Nuvalent Inc.", sector: "Healthcare" },
  "NVCR":   { name: "NovaCure Ltd.", sector: "Healthcare" },
  "OCSL":   { name: "Oaktree Specialty Lending Corp.", sector: "Financials" },
  "ORCC":   { name: "Owl Rock Capital Corp.", sector: "Financials" },
  "ORTX":   { name: "Orchard Therapeutics plc", sector: "Healthcare" },
  "OWL":    { name: "Blue Owl Capital Inc.", sector: "Financials" },
  "PACB":   { name: "Pacific Biosciences of California", sector: "Healthcare" },
  "PAYA":   { name: "Paya Holdings Inc.", sector: "Technology" },
  "PBRA":   { name: "Petróleo Brasileiro SA (Petrobras)", sector: "Energy – Oil & Gas" },
  "PDD":    { name: "PDD Holdings Inc.", sector: "Retail & Leisure" },
  "PLUG":   { name: "Plug Power Inc.", sector: "Clean Energy" },
  "PSEC":   { name: "Prospect Capital Corp.", sector: "Financials" },
  "PTGX":   { name: "Protagonist Therapeutics Inc.", sector: "Healthcare" },
  "PTON":   { name: "Peloton Interactive Inc.", sector: "Retail & Leisure" },
  "QFIN":   { name: "360 DigiTech Inc.", sector: "Financials" },
  "QTS":    { name: "QTS Realty Trust Inc.", sector: "Real Estate" },
  "QURE":   { name: "uniQure NV", sector: "Healthcare" },
  "RACE":   { name: "Ferrari NV (US)", sector: "Automotive" },
  "REPAY":  { name: "Repay Holdings Corp.", sector: "Technology" },
  "REXR":   { name: "Rexford Industrial Realty Inc.", sector: "Real Estate" },
  "RIOT":   { name: "Riot Platforms Inc.", sector: "Crypto & Digital Assets" },
  "RIVN":   { name: "Rivian Automotive Inc.", sector: "Automotive" },
  "RUN":    { name: "Sunrun Inc.", sector: "Clean Energy" },
  "RXRX":   { name: "Recursion Pharmaceuticals Inc.", sector: "Healthcare" },
  "SANA":   { name: "Sana Biotechnology Inc.", sector: "Healthcare" },
  "SE":     { name: "Sea Ltd.", sector: "Technology" },
  "SEDG":   { name: "SolarEdge Technologies Inc.", sector: "Clean Energy" },
  "SELF":   { name: "Global Self Storage Inc.", sector: "Real Estate" },
  "SGMO":   { name: "Sangamo Therapeutics Inc.", sector: "Healthcare" },
  "SKX":    { name: "Skechers USA Inc.", sector: "Retail & Leisure" },
  "SLRC":   { name: "SLR Investment Corp.", sector: "Financials" },
  "SMAR":   { name: "Smartsheet Inc.", sector: "Technology" },
  "SOFI":   { name: "SoFi Technologies Inc.", sector: "Financials" },
  "SPCE":   { name: "Virgin Galactic Holdings Inc.", sector: "Industrials" },
  "SPRK":   { name: "Sparks Group Inc.", sector: "Industrials" },
  "SQ":     { name: "Block Inc.", sector: "Financials" },
  "SQM":    { name: "Sociedad Química y Minera de Chile", sector: "Materials" },
  "STAG":   { name: "STAG Industrial Inc.", sector: "Real Estate" },
  "STEM":   { name: "Stem Inc.", sector: "Clean Energy" },
  "STEP":   { name: "StepStone Group Inc.", sector: "Financials" },
  "SWAV":   { name: "ShockWave Medical Inc.", sector: "Healthcare" },
  "TAL":    { name: "TAL Education Group", sector: "Retail & Leisure" },
  "TCOM":   { name: "Trip.com Group Ltd.", sector: "Retail & Leisure" },
  "TCPC":   { name: "BlackRock TCP Capital Corp.", sector: "Financials" },
  "TCS":    { name: "Container Store Group Inc.", sector: "Retail & Leisure" },
  "TDOC":   { name: "Teladoc Health Inc.", sector: "Healthcare" },
  "TELA":   { name: "TELA Bio Inc.", sector: "Healthcare" },
  "TIGER":  { name: "Tiger Brokers (UP Fintech Holding)", sector: "Financials" },
  "TIGR":   { name: "UP Fintech Holding Ltd.", sector: "Financials" },
  "TMDX":   { name: "TransMedics Group Inc.", sector: "Healthcare" },
  "TME":    { name: "Tencent Music Entertainment Group", sector: "Communication Services" },
  "TPG":    { name: "TPG Inc.", sector: "Financials" },
  "TPVG":   { name: "TriplePoint Venture Growth BDC", sector: "Financials" },
  "UAA":    { name: "Under Armour Inc. Class A", sector: "Retail & Leisure" },
  "UNIT":   { name: "Uniti Group Inc.", sector: "Communication Services" },
  "UP":     { name: "Wheels Up Experience Inc.", sector: "Industrials" },
  "UPST":   { name: "Upstart Holdings Inc.", sector: "Technology" },
  "VALE":   { name: "Vale SA", sector: "Materials" },
  "VFC":    { name: "VF Corp.", sector: "Retail & Leisure" },
  "VKTX":   { name: "Viking Therapeutics Inc.", sector: "Healthcare" },
  "VNET":   { name: "21Vianet Group Inc.", sector: "Technology" },
  "WGMI":   { name: "Valkyrie Bitcoin Miners ETF", sector: "Crypto & Digital Assets" },
  "WIPRO":  { name: "Wipro Ltd. (US ADR)", sector: "Technology" },
  "WIT":    { name: "Wipro Ltd. (ADR)", sector: "Technology" },
  "WMS":    { name: "Advanced Drainage Systems Inc.", sector: "Industrials" },
  "WRBY":   { name: "Warby Parker Inc.", sector: "Retail & Leisure" },
  "XPEV":   { name: "XPeng Inc.", sector: "Automotive" },
  "ZAYO":   { name: "Zayo Group Holdings Inc.", sector: "Communication Services" },
  "ZI":     { name: "ZoomInfo Technologies Inc.", sector: "Technology" },
};

// ─── Apply to DB ──────────────────────────────────────────────────────────────

const rows = db.prepare(
  "SELECT ticker, name, sector FROM universe WHERE sector = 'Other' OR sector IS NULL OR sector = ''"
).all() as any[];

console.log(`Found ${rows.length} stocks in Other`);

const updateSector = db.prepare("UPDATE universe SET sector = ? WHERE ticker = ?");
const updateBoth = db.prepare("UPDATE universe SET name = ?, sector = ? WHERE ticker = ?");

let updatedSector = 0;
let updatedName = 0;
let skipped = 0;

// Per-sector count
const sectorCounts: Record<string, number> = {};

for (const row of rows) {
  const entry = LOOKUP[row.ticker];
  if (!entry) {
    skipped++;
    continue;
  }

  const isBareName = !row.name || row.name === row.ticker || /^[\d\s.]+$/.test(row.name);
  const sectorChanged = entry.sector !== row.sector;
  const nameChanged = isBareName && entry.name;

  if (sectorChanged || nameChanged) {
    if (sectorChanged && nameChanged) {
      updateBoth.run(entry.name, entry.sector, row.ticker);
      updatedSector++;
      updatedName++;
    } else if (sectorChanged) {
      updateSector.run(entry.sector, row.ticker);
      updatedSector++;
    } else if (nameChanged) {
      db.prepare("UPDATE universe SET name = ? WHERE ticker = ?").run(entry.name, row.ticker);
      updatedName++;
    }
    sectorCounts[entry.sector] = (sectorCounts[entry.sector] || 0) + 1;
  }
}

console.log(`\n=== Batch lookup results ===`);
console.log(`Stocks updated (sector): ${updatedSector}`);
console.log(`Stocks updated (name):   ${updatedName}`);
console.log(`Not in lookup map:       ${skipped}`);
console.log(`\nBreakdown by new sector (from Other):`);
Object.entries(sectorCounts)
  .sort(([, a], [, b]) => b - a)
  .forEach(([sector, count]) => console.log(`  ${sector.padEnd(30)} ${count}`));

// Verify remaining Other count
const remaining = db.prepare("SELECT COUNT(*) as n FROM universe WHERE sector = 'Other' OR sector IS NULL OR sector = ''").get() as any;
console.log(`\nRemaining 'Other' after lookup: ${remaining.n}`);

db.close();
