/**
 * seed-universe.ts
 * Populates the universe table from a curated multi-index ticker list.
 * Sources: DataHub.io (S&P500 with metadata), Wikipedia (indices), static curated lists.
 * IMPORTANT: Only ticker symbols and metadata come from here — NO pricing data.
 * All price/fundamental data continues to come from Yahoo Finance / Finnhub in the scheduler.
 */

import { db } from "../server/db";
import { universe } from "../shared/schema";
import { eq } from "drizzle-orm";
import * as fs from "fs";
import * as path from "path";

interface TickerMeta {
  name: string;
  sector: string;
  industry: string;
  exchange: string;
  country: string;
  region: string;
  currency: string;
}

// Load the curated ticker list (generated by fetch script)
const tickerDataPath = path.join(process.cwd(), "scripts", "ticker-data.json");
let allTickers: Record<string, TickerMeta> = {};

if (fs.existsSync(tickerDataPath)) {
  allTickers = JSON.parse(fs.readFileSync(tickerDataPath, "utf-8"));
} else {
  console.error("ticker-data.json not found. Run scripts/fetch-tickers.ts first.");
  process.exit(1);
}

async function seedUniverse() {
  console.log(`[seed-universe] Starting with ${Object.keys(allTickers).length} tickers...`);

  // Get existing tickers
  const existing = db.select({ ticker: universe.ticker }).from(universe).all();
  const existingSet = new Set(existing.map((r) => r.ticker));
  console.log(`[seed-universe] ${existingSet.size} already in DB`);

  let inserted = 0;
  let updated = 0;
  let skipped = 0;

  for (const [ticker, meta] of Object.entries(allTickers)) {
    try {
      if (existingSet.has(ticker)) {
        // Update metadata but keep isActive state
        db.update(universe)
          .set({
            name: meta.name || ticker,
            exchange: meta.exchange || "UNKNOWN",
            country: meta.country || "Unknown",
            region: meta.region || "Unknown",
            currency: meta.currency || "USD",
            sector: meta.sector || null,
            industry: meta.industry || null,
          })
          .where(eq(universe.ticker, ticker))
          .run();
        updated++;
      } else {
        db.insert(universe).values({
          ticker,
          name: meta.name || ticker,
          exchange: meta.exchange || "UNKNOWN",
          country: meta.country || "Unknown",
          region: meta.region || "Unknown",
          currency: meta.currency || "USD",
          sector: meta.sector || null,
          industry: meta.industry || null,
          assetType: "stock",
          isActive: true,
        }).run();
        inserted++;
      }
    } catch (err: any) {
      if (err?.message?.includes("UNIQUE")) {
        skipped++;
      } else {
        console.warn(`[seed-universe] Error for ${ticker}: ${err?.message}`);
        skipped++;
      }
    }
  }

  const total = db.select({ ticker: universe.ticker }).from(universe).all().length;
  console.log(`[seed-universe] Done. Inserted: ${inserted}, Updated: ${updated}, Skipped: ${skipped}`);
  console.log(`[seed-universe] Total in universe: ${total}`);
}

seedUniverse().catch(console.error);
